### ISSUE TITLE
[FLI-92] Document supported hardware architectures

### ISSUE THREAD

**Issue by zamazan4ik** [flipt-io/flipt#1164]
Hi!

I have checked the documentation but did not find any word about supported architectures.

Could you please put the information about supported architectures in the documentation please? E.e. about supported architectures for different operating systems, some specific requirements to the supported instructions, if you have any (e.g. maybe AVX is required - I do not know).

This kind of information is important for the end-users.

Thanks in advance!

<sub>[FLI-92](https://linear.app/flipt/issue/FLI-92/document-supported-hardware-architectures)</sub>

**Comment by markphelps** [comment]
Thanks for the issue! Added info in our docs here: https://www.flipt.io/docs/installation#supported-architectures

**Comment by zamazan4ik** [comment]
@markphelps Could you please specify also supported operating systems? As far as I can understand, only Linux-based OS are supported right now.

**Comment by markphelps** [comment]
@zamazan4ik good idea!

If you do end up needing another arch/OS support please let us know. Should be relatively easy to support since we're in Go.

![CleanShot 2022-12-28 at 15 31 23](https://user-images.githubusercontent.com/209477/209868864-fd1fe873-f19d-4cd8-a4ee-a7d0c2056ac1.png)
