### ISSUE TITLE
[FLI-96] Document Grafana dashboards

### ISSUE THREAD

**Issue by zamazan4ik** [flipt-io/flipt#1165]
### Problem

Is your feature request related to a problem? Please describe:

Flipt provides a set of metrics: https://www.flipt.io/docs/configuration#metrics . However, for the end-users is much easier to use already provided Grafana dashboards (and in some cases just tweak them a little bit).

### Ideal Solution

Describe the solution you'd like:

Add Flipt-provided Grafana dashboards.

<sub>[FLI-96](https://linear.app/flipt/issue/FLI-96/document-grafana-dashboards)</sub>

**Comment by markphelps** [comment]
Hi @zamazan4ik ! Thanks for the issue! We just recently created https://github.com/flipt-io/grafana-dashboards. Does this cover your use case? 

We are planning to blog/post about it early next week!

**Comment by zamazan4ik** [comment]
Yeah, looks pretty good! Would be awesome to see this information in the documentation. Thank you.
