### ISSUE TITLE
[FLI-93] Document Highly-Available (HA) setup

### ISSUE THREAD

**Issue by zamazan4ik** [flipt-io/flipt#1166]
After reading the documentation about the project architecture (https://www.flipt.io/docs/architecture) it is not clear to me, how could I perform Flipt HA setup. I have questions like:
- Could I install Flipt in cluster mode (multiple nodes in one installation)?
- If yes, how Flipt works if one node goes down? is there any (semi)automatic failover or not?

Similar questions regarding scaling - how the solution should be scaled?

Would be awesome to read about it directly in the documentation.

<sub>[FLI-93](https://linear.app/flipt/issue/FLI-93/document-highly-available-ha-setup)</sub>

**Comment by markphelps** [comment]
Its like you are reading our minds @zamazan4ik ! This, #1167 and #1168 are all apart of our documentation improvements that we have planned. Will keep this open, but expect these additions to the documentation soon!

**Comment by zamazan4ik** [comment]
Maybe :) Do you have a public-available roadmap for the documentation? Just to compare my own questions with your roadmap and prevent "spamming" extra issues :)

**Comment by markphelps** [comment]
No public docs roadmap, but we're basically thinking of splitting the docs into two subsections, one for 'operators' who are in charge or installing/running Flipt and keeping it up to date, and another for 'users' who may not set it up, but will integrate with it. This may end up being the same person, but depends on the org.

Here's the general thinking:

```
> Operator Guide
    > Architecture
    > Installation
        - Docker
        - Helm/K8s
        - Binary
    > Configuration
    > Authentication
    > Security Best Practices
    > High Availability
    > Backup / Disaster Recovery
    > Persistence
    > Caching
    > Bootstrapping
    > Metrics
    > Upgrading
    
> User Guide 
    > Integration
       > REST API
       > GRPC API
    > Client SDKs
    > Authentication
    > Tracing
    > Metrics
```

Would love to know what other docs you would love to see, on either 'side'

**Comment by zamazan4ik** [comment]
Just want to add a note about downgrade support as well. It is quite important for the users in case if something goes wrong during the update process.

**Comment by GeorgeMac** [comment]
FYI we added the docs here https://www.flipt.io/docs/operations/deployment
Hopefully that addresses some questions around a high availability setup for Flipt.

**Comment by zamazan4ik** [comment]
@GeorgeMac just a quick addition: "Postgres" -> "PostgreSQL". https://www.postgresql.org/
