### ISSUE TITLE
[FLI-94] Document upgrade/downgrade processes

### ISSUE THREAD

**Issue by zamazan4ik** [flipt-io/flipt#1167]
After reading the documentation I have the following questions regarding upgrade/downgrade processes:
- How the upgrade should be performed?
- Is it possible to upgrade without downtime?
- How the downgrade should be performed? Is downgrade processes supported
- Is it possible to downgrade without downtime?
- Also, could be quite useful to know about compatibility guarantees between releases

<sub>[FLI-94](https://linear.app/flipt/issue/FLI-94/document-upgradedowngrade-processes)</sub>

**Comment by WDaan** [comment]
Are there any plans to make the update process automatic? e.g. an initContainer that runs the migration?
What's the recommended way of doing these upgrades currently?
