### ISSUE TITLE
[FLI-146] Unable to save flag after modifying & saving

### ISSUE THREAD

**Issue by cxnky** [flipt-io/flipt#1259]
### Describe the Bug

When I enable a flag, save it and then disable it again - the save button doesn't re-enable, meaning I have to go back to the flag list and back onto the flag

### Version Info

Run `flipt --version` and paste the output here:
v1.17-rc2

### To Reproduce
Open a flag, toggle the "Enabled" option, save it, then toggle it again

### Expected Behavior
The save button should re-enable

### Additional Context

GIF showing the issue: https://i.imgur.com/UsYkb3J.gif

Examples:

- OS
- Config file used
- Database used (SQLite, MySQL, or Postgres)
- Screenshots
- Exported data from the database

<sub>[FLI-146](https://linear.app/flipt/issue/FLI-146/unable-to-save-flag-after-modifying-and-saving)</sub>

**Comment by markphelps** [comment]
Moving this to our internal issue tracker. Thanks again @cxnky !
