### ISSUE TITLE
Optional public evaluate route

### ISSUE THREAD

**Issue by WDaan** [flipt-io/flipt#1351]
### Problem

We would like to use Flipt as a general feature-flag service. So both frontend/backend services will want to evaluate their flags.
The management dashboard will be secured using SSO.

However, when you enable authentication, this is enabled for all routes...meaning no flags can be evaluated anymore without providing proper authentication. When using a static token, you immediately provide access to the whole CRUD api.

For a frontend project, we cannot simply set a static token on the frontend side so we would have to proxy all the requests and attach the token somewhere else.

Whole discussion can be read [here](https://discord.com/channels/960634591000014878/1077577986695507999)

### Ideal Solution

As mentioned in the discussion, a more granular token based auth system is on the roadmap, however we're not there yet.
The solution I propose for this kind of use-case is to create another setting that toggles public access to the `evaluate`-endpoint.

That way new flags can be securely created and managed using SSO and all services are allowed to evaluate their flags (which don't cause any risk).

[example implementation](https://github.com/WDaan/flipt/commit/86528965e9c06c328c557d14531db1f00ffbee53)

Let me know what you think.
Thanks!

**Comment by WDaan** [comment]
Reopen

**Comment by markphelps** [comment]
Yeah we def want to figure out a way to accomplish this that perhaps doesn't only limit to the `evaluate` / `batch-evaluate` routes. I can see people wanted to expose the GET Flag route publicly as well without auth

**Comment by markphelps** [comment]
FYI we are tackling this with the work done to solve #368

Should be out within the next two weeks or so for anyone interested to try. Will keep this issue updated as well

**Comment by WDaan** [comment]
Awesome! Thanks for the great work so far and keeping this up to date :)
