### ISSUE TITLE
docker installation

### ISSUE THREAD

**Issue by satishviswanathan** [flipt-io/flipt#1517]
### Describe the Bug

Docker installation

### To Reproduce

docker run -d \
    -p 8080:8080 \
    -p 9000:9000 \
    -v $HOME/flipt:/var/opt/flipt \
    flipt/flipt:latest

### Expected Behavior

Instance should be accessible in port 8080.

**Comment by yquansah** [comment]
Hello @satishviswanathan 👋 

Thank you for filing this issue, do you mind showing the log output of your container, with `docker logs`? Also a bit more information on where you are running this (locally, remotely, etc.).

**Comment by GeorgeMac** [comment]
@satishviswanathan does Flipt product any logs when you do this? If so, could you share them here.
We’re struggling to reproduce the issue.

**Comment by satishviswanathan** [comment]
Thank you all for the quick response. Sharing the log from docker.



EXITED (2)



runtime/cgo: pthread_create failed: Operation not permitted

SIGABRT: abort

PC=0x106281c m=0 sigcode=18446744073709551610


goroutine 0 [idle]:

runtime: g 0: unknown pc 0x106281c

stack: frame={sp:0x7fff6dc73e20, fp:0x0} stack=[0x7fff6d4753a0,0x7fff6dc743b0)

0x00007fff6dc73d20: 0x0000000000405c20 <runtime.mmap.func1+0x0000000000000000> 0x00007fff6dc73d18

0x00007fff6dc73d30: 0x00007f0f45fdd000 0x0000000000407000 <runtime.cgoIsGoPointer+0x0000000000000040>

0x00007fff6dc73d40: 0x0000003200000003 0x00000000ffffffff

0x00007fff6dc73d50: 0x00007fff6dc73d98 0x000000000041a2b9 <runtime.sysMapOS+0x0000000000000039>

0x00007fff6dc73d60: 0x00007f0f43ec8000 0x0000000000405c20 <runtime.mmap.func1+0x0000000000000000>

0x00007fff6dc73d70: 0x000000000041a23a <runtime.sysHugePageOS+0x000000000000005a> 0x00007f0f46000000

0x00007fff6dc73d80: 0x0000000000200000 0x000000000000000e

0x00007fff6dc73d90: 0x00007f0f00000000 0x00007fff6dc73dc8

0x00007fff6dc73da0: 0x000000000041a147 <runtime.sysUsedOS+0x0000000000000027> 0x000000000104b150

0x00007fff6dc73db0: 0x0000000000407000 <runtime.cgoIsGoPointer+0x0000000000000040> 0x0000000000000000

0x00007fff6dc73dc0: 0x0000000000000120 0x000000126dc73e38

0x00007fff6dc73dd0: 0x00000000010e3e30 0x000000001c000004

0x00007fff6dc73de0: 0x0000000000000110 0x0000000000000000

0x00007fff6dc73df0: 0x0000000000002000 0x00007f0f6b1091c8

0x00007fff6dc73e00: 0x0000000000000004 0x0000003400000012

0x00007fff6dc73e10: 0x0000000000000000 0x000000000106280e

0x00007fff6dc73e20: <0x0000000000000000 0x000000770000007c

0x00007fff6dc73e30: 0x0000005b0000006e 0x0000000001fd2d00

0x00007fff6dc73e40: 0x00007fff6dc74060 0x00000000010a05e1

0x00007fff6dc73e50: 0x00007f0f43da7640 0x00007fff6dc74130

0x00007fff6dc73e60: 0x00007fff6dc73f9e 0x00007fff6dc73f9f

0x00007fff6dc73e70: 0x0000000000000000 0x0000000001060c99

0x00007fff6dc73e80: 0x0000000000800280 <net/http.(*timeoutWriter).writeHeaderLocked+0x0000000000000260> 0x0007140038a00000

0x00007fff6dc73e90: 0x00000000003d0f00 0x00007f0f43da7910

0x00007fff6dc73ea0: 0x00007f0f43da7910 0x26d00cfb33810800

0x00007fff6dc73eb0: 0x0000000002c623c0 0x0000000000000006

0x00007fff6dc73ec0: 0x000000000179818e 0x00007fff6dc741f0

0x00007fff6dc73ed0: 0x0000000001fbabc0 0x0000000001053d36

0x00007fff6dc73ee0: 0x0000000001fea960 0x00000000004013c1

0x00007fff6dc73ef0: 0x0000000000000020 0x00007f0f43da7640

0x00007fff6dc73f00: 0x0000000000000000 0x00007fff6dc74130

0x00007fff6dc73f10: 0x00007f0f43da7640 0x0000000001061aca

runtime: g 0: unknown pc 0x106281c

stack: frame={sp:0x7fff6dc73e20, fp:0x0} stack=[0x7fff6d4753a0,0x7fff6dc743b0)

0x00007fff6dc73d20: 0x0000000000405c20 <runtime.mmap.func1+0x0000000000000000> 0x00007fff6dc73d18

0x00007fff6dc73d30: 0x00007f0f45fdd000 0x0000000000407000 <runtime.cgoIsGoPointer+0x0000000000000040>

0x00007fff6dc73d40: 0x0000003200000003 0x00000000ffffffff

0x00007fff6dc73d50: 0x00007fff6dc73d98 0x000000000041a2b9 <runtime.sysMapOS+0x0000000000000039>

0x00007fff6dc73d60: 0x00007f0f43ec8000 0x0000000000405c20 <runtime.mmap.func1+0x0000000000000000>

0x00007fff6dc73d70: 0x000000000041a23a <runtime.sysHugePageOS+0x000000000000005a> 0x00007f0f46000000

0x00007fff6dc73d80: 0x0000000000200000 0x000000000000000e

0x00007fff6dc73d90: 0x00007f0f00000000 0x00007fff6dc73dc8

0x00007fff6dc73da0: 0x000000000041a147 <runtime.sysUsedOS+0x0000000000000027> 0x000000000104b150

0x00007fff6dc73db0: 0x0000000000407000 <runtime.cgoIsGoPointer+0x0000000000000040> 0x0000000000000000

0x00007fff6dc73dc0: 0x0000000000000120 0x000000126dc73e38

0x00007fff6dc73dd0: 0x00000000010e3e30 0x000000001c000004

0x00007fff6dc73de0: 0x0000000000000110 0x0000000000000000

0x00007fff6dc73df0: 0x0000000000002000 0x00007f0f6b1091c8

0x00007fff6dc73e00: 0x0000000000000004 0x0000003400000012

0x00007fff6dc73e10: 0x0000000000000000 0x000000000106280e

0x00007fff6dc73e20: <0x0000000000000000 0x000000770000007c

0x00007fff6dc73e30: 0x0000005b0000006e 0x0000000001fd2d00

0x00007fff6dc73e40: 0x00007fff6dc74060 0x00000000010a05e1

0x00007fff6dc73e50: 0x00007f0f43da7640 0x00007fff6dc74130

0x00007fff6dc73e60: 0x00007fff6dc73f9e 0x00007fff6dc73f9f

0x00007fff6dc73e70: 0x0000000000000000 0x0000000001060c99

0x00007fff6dc73e80: 0x0000000000800280 <net/http.(*timeoutWriter).writeHeaderLocked+0x0000000000000260> 0x0007140038a00000

0x00007fff6dc73e90: 0x00000000003d0f00 0x00007f0f43da7910

0x00007fff6dc73ea0: 0x00007f0f43da7910 0x26d00cfb33810800

0x00007fff6dc73eb0: 0x0000000002c623c0 0x0000000000000006

0x00007fff6dc73ec0: 0x000000000179818e 0x00007fff6dc741f0

0x00007fff6dc73ed0: 0x0000000001fbabc0 0x0000000001053d36

0x00007fff6dc73ee0: 0x0000000001fea960 0x00000000004013c1

0x00007fff6dc73ef0: 0x0000000000000020 0x00007f0f43da7640

0x00007fff6dc73f00: 0x0000000000000000 0x00007fff6dc74130

0x00007fff6dc73f10: 0x00007f0f43da7640 0x0000000001061aca


goroutine 1 [running]:

runtime.systemstack_switch()

runtime/asm_amd64.s:463 fp=0xc00007c780 sp=0xc00007c778 pc=0x46f9e0

runtime.main()

runtime/proc.go:170 +0x6d fp=0xc00007c7e0 sp=0xc00007c780 pc=0x43d62d

runtime.goexit()

runtime/asm_amd64.s:1598 +0x1 fp=0xc00007c7e8 sp=0xc00007c7e0 pc=0x471c01


rax 0x0

rbx 0x2c623c0

rcx 0x106281c

rdx 0x6

rdi 0x1

rsi 0x1

rbp 0x1

rsp 0x7fff6dc73e20

r8 0x7fff6dc73ef0

r9 0x0

r10 0x8

r11 0x246

r12 0x6

r13 0x16

r14 0x1fbabc0

r15 0x1

rip 0x106281c

rflags 0x246

cs 0x33

fs 0x0

gs 0x0

**Comment by yquansah** [comment]
@satishviswanathan Could you try running without the volume mount to see if you can boot the container up? Also, is it exiting on startup, or exitig once you make a request?

**Comment by satishviswanathan** [comment]
@yquansah  I tried removing the mount path but still getting the same error. I'm getting this error on startup.

**Comment by GeorgeMac** [comment]
Hey @satishviswanathan seems like this is related to this https://github.com/containers/skopeo/issues/1501

Could you check what version of Docker you’re running for us? I think docker -v should show it.

**Comment by satishviswanathan** [comment]
@GeorgeMac 

Yes seems to be same error.

Docker version

Docker version 19.03.13, build 4484c46d9d

**Comment by GeorgeMac** [comment]
Is it possible for you to upgrade your docker instance @satishviswanathan? There’s a good chance it might work if you upgrade docker.

**Comment by satishviswanathan** [comment]
Thank you Let me try that out.

**Comment by satishviswanathan** [comment]
Thank you for the support that worked !
