### ISSUE TITLE
[FLI-338] Export functionality acting weird

### ISSUE THREAD

**Issue by pdonorio** [flipt-io/flipt#1553]
### Describe the Bug

Using the `export` command over an existing flipt file,
existing flags get canceled and new flags don't get added.

### Version Info

```
Version: 1.20.1
Commit: cfc5af804882c5c62b5bc7e77675bfde49fc91d3
Build Date: 2023-04-27T13:30:43Z
Go Version: go1.20.3
```

### To Reproduce

Use a `flipt.yaml` that was manually modified for some flags,
but that is correctly read, e.g. opening the UI we see all the flags.

Run `./flipt export -o YOURFILE`, and see existing flags were removed.
Adding DEBUG doesn't show anything useful.

Add flags from the UI, run export and see no new flags stored in `flipt.yaml`.

### Expected Behavior

Export not removing valid feature flags, and adding new flags created through the UI.

### Additional Context

I can't attach the file but there's nothing looking strange in the flags removed.

Difficult to say from which version this is happening (also v1.19.2 has the same problem)
and if it might be due to not having all the flags generated with exports.

Let me know how I can help more 🙏🏽 

<sub>[FLI-338](https://linear.app/flipt/issue/FLI-338/export-functionality-acting-weird)</sub>

**Comment by markphelps** [comment]
👋🏻 Hi @pdonorio 

Thanks for reporting!

I wanted to ask some follow up questions to make sure I understand the issue.

> Use a flipt.yaml that was manually modified for some flags, but that is correctly read, e.g. opening the UI we see all the flags.

Do you mean you modify `flipt.yaml` and then run `flipt import` with that file? 

`flipt export` shouldn't read anything from the existing `flipt.yaml`, it should only write the contents of data stored in the database to yaml. (I'm not saying there isn't a bug, just want to make sure I understand the issue).

**Comment by markphelps** [comment]
Oh, one thing I can think of, is that in `v1.20.0` we added support for [namespaces](https://www.flipt.io/docs/concepts#namespaces), but migrated all flags to the 'default' namespace.

So if you are running `v1.20.0`+, and run `flipt export -o flipt.yaml` it will only write flags from the 'default' namespace. If you have flags under a different namespace then you will need to do `flipt export --namespace {namespace_key} -o flipt.yaml`. https://www.flipt.io/docs/configuration/storage#export

I could see how this would not write out all the flags that you see in the UI, if you are in fact using multiple namespaces, although it doesn't explain how `v1.19.2` has this problem since namespace feature was not added then.

**Comment by pdonorio** [comment]
Hi @markphelps thanks a ton for the quick response!

> Do you mean you modify `flipt.yaml` and then run `flipt import` with that file?

No, what I meant was: 
modifying the `flipt.yaml` manually, and then re-run the service upon the modified file
(instead of modifying the flags through the UI and running export, before re-running the service).

> if you are running v1.20.0+, and run flipt export -o flipt.yaml it will only write flags from the 'default' namespace

Thanks for the idea! I've just double checked now and we're using only the default namespace, so that's not the problem.

I was wondering, is there anyway flipt would not export a flag that it's available to see in the UI?

I'm not sure how to replicate exactly the issue with a minimal set, maybe I can try to have a file with one flag that is saved and one that is not and re-run the export to see what happens. I'll see if I can try that later.

**Comment by GeorgeMac** [comment]
Hey @pdonorio,

I am still trying to picture what you're observing, but I thought I would share some of the expectations of how `export` works incase it helps.

The file path given to export as the target, if it exists, is truncated (cleared) before writing.
Then it simply fills the (now empty) file with the namespace contents being referenced.
Anything in the file, that is not currently in the instance being exported, will be removed.

Does this help explain what you're observing, or is there something more bizarre I am not seeing?

**Comment by pdonorio** [comment]
Hi @GeorgeMac, thanks for your explanation.
Yes, that was what we were expecting, but not what we're getting.

What happens:
- load the service from a `flipt.yaml` file, verify that it worked from the UI 
- add new flags in the UI, do not remove any existing one
- export the running service to the same `flipt.yaml` file

resulting in: new flags are not found in the file, some existing ones were removed.

I apologies for not having time to try and create a dummy small file to help reproduce, been busy with other things. Trying to get to this again tomorrow 🤞🏽

**Comment by GeorgeMac** [comment]
No worries @pdonorio. Your description here is very useful. I will see what I can replicate my end too.

**Comment by GeorgeMac** [comment]
```
 _____ _ _       _
|  ___| (_)_ __ | |_
| |_  | | | '_ \| __|
|  _| | | | |_) | |_
|_|   |_|_| .__/ \__|
          |_|

Version: dev
Commit: 830ec4e8cc7e033f2eef0de53409fe3a51a0b0de
Build Date: 2023-05-03T08:29:08Z
Go Version: go1.20.2
```

(Built off current main)

With a simple SQLite setup (and the build above) I have managed to do the following steps successfully.
The following are all run from the root of the flipt repo after building (running `mage`):

1. Import a config yaml

```
# from root of Flipt project
./bin/flipt import --config ./config/local.yml build/testing/integration/readonly/testdata/seed.yaml
```
2. Check the contents matches in the UI
3. Add a new flag (I named it `language`).
4. Export Flipt into the original yaml file
```
./bin/flipt export --config ./config/local.yml -o build/testing/integration/readonly/testdata/seed.yaml
```
5. Check the changed file (contains the flag I added).
```diff
diff --git a/build/testing/integration/readonly/testdata/seed.yaml b/build/testing/integration/readonly/testdata/seed.yaml
index 0aacd817..5108f2f5 100644
--- a/build/testing/integration/readonly/testdata/seed.yaml
+++ b/build/testing/integration/readonly/testdata/seed.yaml
@@ -1,3 +1,5 @@
+# exported by Flipt (dev) on 2023-05-03T08:30:53Z
+
 flags:
 - key: color
   name: Color
@@ -19,6 +21,9 @@ flags:
     distributions:
     - variant: blue
       rollout: 100
+- key: language
+  name: language
+  enabled: true
 segments:
 - key: team-red
   name: Red Team
```

It would be great to get some more context on your setup @pdonorio .
The weird behaviour could be surfacing under other configuration setups.
e.g. different DB, import/export through flipt api (`export --address`) or faults in the export yaml perhaps.

If we could information e.g.:
- Flipt version
- Config file (redacted of any secrets)
- Your import/export yaml files (also redacted of any sensitive info)

These would be a massive help 🙏

**Comment by pdonorio** [comment]
Hey @GeorgeMac thanks a lot for your useful post 🙏🏽 

I had a chance to play with my local flipt YAML file 
and finally found (after a billion of remove and test import/export 😆 ) 
at least which flag is causing trouble.

It's the one that uses variants. It looks something like:

```yaml
- key: feature_blabla
  name: FEATURE_BLABLA
  description: bla bla
  enabled: true
  variants:
  - key: all
    name: all
    description: All of it
    attachment:
      values:
      - one
      - two
      - three
  - key: some
    name: some
    description: Only some
    attachment:
      values:
      - four
  rules:
  - segment: my_segment
    rank: 1
    distributions:
    - variant: all
    - variant: some
      rollout: 100
```

If I don't have this one, all works.

I'm trying to understand what is wrong with it by recreating it through the UI.

**Comment by markphelps** [comment]
Thanks @pdonorio !! Will add this to our unit tests and see if we can re-create the issue/get to the bottom of this. your example is a huge help!!

**Comment by pdonorio** [comment]
Did some more testing and it's not clear what the problem is :/ 

The new version from the UI works, but doesn't seem to change anything really.
I thought it was some bad char or weird space but if I put the original order of the flags back with the new versions, still it gives the problem 🤯 

I'm not sure what to do to isolate deterministically the real problem, but the position seems related.
Would you know?

In the meantime we'll use the one version that works.

**Comment by pdonorio** [comment]
For the record, to test my changes on the file I just do on a running flipt container:

```bash
# load
/ $ ./flipt import --drop /opt/flags/flipt.yaml
# export
/ $ ./flipt export -o /opt/flags/flipt.yaml
# check git diff
```

**Comment by GeorgeMac** [comment]
How many flags and segments do you have in your set @pdonorio ?
Starting to wonder if perhaps we're a pagination bug.
The exporter lists using pagination. If you have a number of flags closer to the page boundary, then we might have an off by one problem.

**Comment by GeorgeMac** [comment]
I do have a sneaking suspicion pagination is the problem here. Going to create a reproduction of what I think is happening in tests.

**Comment by pdonorio** [comment]
@GeorgeMac around ~35 flags, so only two pages.

If pagination is in any way related to export that could make sense, given that changing the order is solving the problem and the one flag example I posted is the longest in the file?

**Comment by GeorgeMac** [comment]
I think I found the bug ☝️ Appreciate you reporting this @pdonorio 🙏

**Comment by pdonorio** [comment]
> I think I found the bug ☝️ Appreciate you reporting this @pdonorio 🙏

Oh wow, amazing idea and investigation @GeorgeMac 👏🏽

**Comment by markphelps** [comment]
@pdonorio this was autoclosed by CI, but we are releasing versions:

- v1.19.5
- v1.20.2
- v1.21.1

which should contain the fix for this issue 🌮

**Comment by GeorgeMac** [comment]
Those should all be released now @pdonorio 👍 

We would love to know if it solves your problem whenever you get a moment to test 🙏

**Comment by pdonorio** [comment]
@GeorgeMac that was fast :O 

Pulling the latest 1.21.1 docker image and checking!

**Comment by pdonorio** [comment]
Putting the original order back it works!! No more removal of flags 👏🏽 
Thanks a lot!!!! @GeorgeMac @markphelps <3

**Comment by GeorgeMac** [comment]
Amazing. Thanks again for the issue!
