### ISSUE TITLE
[FLI-375] version 1.22 does not accept Description as null

### ISSUE THREAD

**Issue by tomaszmichalowski** [flipt-io/flipt#1653]
### Describe the Bug

After upgrading flipt from v1.19.3 to 1.22.0 and description field on flags where empty (NULL) . 

`sql: Scan error on column index 7, name "description": converting NULL to string is unsupported`

### Version Info

1.22.0

### To Reproduce

1. Install version 1.19.3
2. Create Segment with empty description field 
3. Upgrade to version 1.22.0
4. go to Segments -> chose segment
`sql: Scan error on column index 7, name "description": converting NULL to string is unsupported`

### Expected Behavior

No error shown

### Additional Context

Probably there is a problem in the migration script when converting Description values. 

Examples:

- OS
- Config file used
- Database used (SQLite, MySQL, or Postgres)
- Screenshots
- Exported data from the database

<sub>[FLI-375](https://linear.app/flipt/issue/FLI-375/version-122-does-not-accept-description-as-null)</sub>

**Comment by markphelps** [comment]
Thanks for reporting @tomaszmichalowski ! We're working on a fix now. Will have it out in a bit

**Comment by markphelps** [comment]
@tomaszmichalowski should be fixed in the latest release v1.22.1 🎉 . Thanks again for reporting!

**Comment by markphelps** [comment]
idk why this keeps getting reopened

**Comment by GeorgeMac** [comment]
I think I accidentally typed FLI-375 on this one https://github.com/flipt-io/flipt/pull/1763 and then corrected it to FLI-376 and since then it wont give up on these being linked.

**Comment by GeorgeMac** [comment]
I've removed the link. Lets see if it stays closed.
