### ISSUE TITLE
Etcd storage backend

### ISSUE THREAD

**Issue by gavincabbage** [flipt-io/flipt#174]
**Is your feature request related to a problem? Please describe.**
Since my systems already use Etcd as a storage backend, an Etcd backend for Flipt would make it easier to deploy in my environment.

**Describe the solution you'd like**
I would like an Etcd storage backend, in addition to the PostgreSQL and SQLite options.

**Additional context**
Adding an Etcd backend will be a shift from the SQL backends currently offered, but hopefully any work towards Etcd would also be useful towards supporting other KV backends, like Redis.

**Comment by markphelps** [comment]
Let me know if I can help @gavincabbage !!
