### ISSUE TITLE
[FLI-498] Allow 'and'-ing of Segments in Rules [Converted to "Allow 'and'-ing of Segments in Rules" project]

### ISSUE THREAD

**Issue by markphelps** [flipt-io/flipt#1882]
We've had a few requests to allow specifying multiple segments when setting up a Rule, basically 'Anding' them together.

We should look into what would be required to implement this feature, both from the API(s), import/export, and UI perspectives

We should also look into how we could support this with the new 'rollouts' UI coming in [FLI-230](https://linear.app/flipt/issue/FLI-230/make-flag-rollout-a-first-class-feature)

We could also allow for explicit 'or' ing of segments within a rule as well.

<sub>From [SyncLinear.com](https://synclinear.com) | [FLI-498](https://linear.app/flipt/issue/FLI-498/allow-and-ing-of-segments-in-rules-[converted-to-allow-and-ing-of)</sub>

**Comment by markphelps** [comment]
cc @jalaziz

**Comment by markphelps** [comment]
Dupe of https://github.com/flipt-io/flipt/issues/732 (Sorry for closing!) Will just keep this issue updated going forward

**Comment by markphelps** [comment]
Hey @jalaziz ! This is now released in the latest version v1.25! Thanks for the suggestion, let us know how it works for you!

**Comment by jalaziz** [comment]
Hell yeah! Didn't expect this to be fixed that quick. Amazing! 🙏🏼

**Comment by markphelps** [comment]
All thanks to @yquansah ! He did all the hard work
