### ISSUE TITLE
[FLI-531] User theme preference should be persisted. 

### ISSUE THREAD

**Issue by charlesoconor** [flipt-io/flipt#1933]
### Describe the Bug

When a session has expired, the UI will be reset to the theme, "Light". Would persist until the user makes a change. 

Not a huge deal but I like using the dark mode. 

### Version Info

```
 _____ _ _       _
|  ___| (_)_ __ | |_
| |_  | | | '_ \| __|
|  _| | | | |_) | |_
|_|   |_|_| .__/ \__|
          |_|

Version: v1.24.0
Commit: 2df57db6bcec306346e364a793fba422f2f9a93a
Build Date: 2023-07-31T13:54:06Z
Go Version: go1.20.6
```

### To Reproduce

Change UI theme to anything besides light. Wait for the session to be revoked. The theme will be reset to the default. 

<sub>[FLI-531](https://linear.app/flipt/issue/FLI-531/user-theme-preference-should-be-persisted)</sub>

**Comment by markphelps** [comment]
💯 , i encountered this before and totally forgot to file an issue. Thanks for bringing it to our attention! Will get it fixed!

**Comment by markphelps** [comment]
Was able to reproduce using the [Dex OIDC example](https://github.com/flipt-io/flipt/tree/main/examples/authentication/dex)

1. cd `examples/authentication/dex`
2. docker-compose up --build
3. login with `admin@example.com/password`
4. change them to dark
5. logout
6. login again
7. see theme is back to light (local storage is cleared)

![CleanShot 2023-07-31 at 16 55 05](https://github.com/flipt-io/flipt/assets/209477/ca5090ad-689a-46ce-9864-3fe924d5fb3e)

![CleanShot 2023-07-31 at 16 55 36](https://github.com/flipt-io/flipt/assets/209477/0dc6d4c3-c31a-4dd9-9dbd-b4492258be88)

**Comment by charlesoconor** [comment]
Just upgraded my instance. Looks like its working. Thank you!
