### ISSUE TITLE
[FLI-536] Configuration JSON Schema missing authentication.methods.oidc.providers.[provider].scopes

### ISSUE THREAD

**Issue by Provinite** [flipt-io/flipt#1944]
### Describe the Bug
The JSON schema at [config/flipt.schema.json](https://raw.githubusercontent.com/flipt-io/flipt/main/config/flipt.schema.json) is missing a definition for the OIDC OAuth scopes configuration option (`authentication.methods.oidc.providers.[provider].scopes`), which is documented here https://www.flipt.io/docs/configuration/overview

### Version Info
1.23.3 (I'm using the docker container. I wasn't sure how to invoke the CLI to get the full version output)

### To Reproduce
- Create a flipt YML config referencing the JSON schema that utilizes the aforementioned configuration key

### Expected Behavior
- Configuration file passes schema validation (I'm using the VSCode YAML features extension to do so)

### Additional Context
This is a configuration file that I believe should pass validation but does not.

```default.yml
# yaml-language-server: $schema=https://raw.githubusercontent.com/flipt-io/flipt/main/config/flipt.schema.json
server:
  protocol: http
  host: '0.0.0.0'
  https_port: 443
  http_port: 8080
  grpc_port: 9000
db:
  url: postgres://dbuser:password@postgres:5432/flipt
  max_idle_conn: 2
authentication:
  required: true
  session:
    domain: localhost:8080
    secure: false
  methods:
    oidc:
      enabled: true
      email_matches:
        - ^.*@polco.us$
      providers:
        google:
          issuer_url: https://accounts.google.com
          client_id: ... omitted due to the writer's strike...
          client_secret: ...omitted to save bytes...
          redirect_address: http://localhost:8080
          scopes: # <--- Squiggly line
            - email
            - profile
```

Thanks for taking the time to read, let me know if I've goofed up anywhere or can provide additional info.

<sub>[FLI-536](https://linear.app/flipt/issue/FLI-536/configuration-json-schema-missing)</sub>

**Comment by markphelps** [comment]
Thanks for the issue @Provinite ! we've had quite the time of ensuring that our JSONSchema reflects reality of what is possible with the config. We're working on automating this in CI..

Will fix this ASAP!

**Comment by Provinite** [comment]
Thanks! if it's just a matter of updating the schema(s) manually, I could take a stab at a PR if that's helpful.

**Comment by markphelps** [comment]
That would be great @Provinite . Yup it should just be adding the property to the JSON Schema `config/flipt.schema.json` and Cue Schema if you don't mind `config/flipt.schema.json`

Once its merged to main that squiggly should go away in your IDE
