### ISSUE TITLE
[FLI-538] feat: add an ENV variable to default theme

### ISSUE THREAD

**Issue by markphelps** [flipt-io/flipt#1952]
Would it make sense to add an ENV variable to force a specific theme for everyone?

_Originally posted by @gaby in https://github.com/flipt-io/flipt/issues/1933#issuecomment-1660262838_
            

<sub>[FLI-538](https://linear.app/flipt/issue/FLI-538/feat-add-an-env-variable-to-default-theme)</sub>

**Comment by markphelps** [comment]
This would be a good first issue for anyone interested in implementing

I think it would require the following changes:

1. Add a field here `ui.default_theme` https://github.com/flipt-io/flipt/blob/4a8352ae9bb4d854d4e04022ccbba5dd99f4553a/internal/config/ui.go#L11 with enum options of `system, dark, light`
2. Populate the local storage item (https://github.com/flipt-io/flipt/blob/4a8352ae9bb4d854d4e04022ccbba5dd99f4553a/ui/src/store.ts#L43) from this selector `https://github.com/flipt-io/flipt/blob/4a8352ae9bb4d854d4e04022ccbba5dd99f4553a/ui/src/app/meta/metaSlice.ts#L51C17-L51C17` for `theme.

The flow would be:
1. Flipt UI reads the `ui.default_theme` property from the JSON response of the `/config` endpoint call
2. Flipt UI sets that value in localstorage if it doesn't exist, which then the UI will use as the default theme

**Comment by Jamess-Lucass** [comment]
I'd be interested in taking this one to get acquainted with the repo.
