### ISSUE TITLE
[FLI-558] Investigate HTTPS Support

### ISSUE THREAD

**Issue by GeorgeMac** [flipt-io/flipt#1972]
### Describe the Bug

See Discord for original issue: https://discord.com/channels/960634591000014878/1123489431249236038/1137178755006210072

A user reported issues using self-generated TLS certificates and running Flipt with HTTPS.
Flipt ultimately failed fast with:

```
2023-08-04T23:59:08Z    FATAL    flipt    {"error": "context deadline exceeded"}
```

My suspicion here is that the error is pertaining to the gateway client dialing the gRPC server internally in Flipt and then timing out on the dial timeout.

I had one guess, which was that the client was failing to verify the server, because it did not have the CA certificate in its trusted roots. However, we haven't proved that is part of the problem yet. One attempt was made to update the CA certificates in the Docker image. However, the user had no luck with that approach.

In the end they settled on using NGinx infront of Flipt.

We should investigate further to see if there is something going on with the setup.

### Version Info

```
Version: v1.24.1
Commit: b4285ae1e352c2f30cc9a5e1a92deea1355c622f
Build Date: 2023-08-01T15:12:31Z
Go Version: go1.20.6
```

### To Reproduce

1. Generate a set of certificates following the instructions [here](https://dev.to/techschoolguru/how-to-secure-grpc-connection-with-ssl-tls-in-go-4ph).
2. Configure Flipt using the following details:
```yaml
server:
  protocol: https
  host: feature-flag
  cert_file: /etc/flipt/config/server-cert.pem
  cert_key: /etc/flipt/config/server-key.pem
```
> Note that the user had also explicitly set the `host` parameter. This might be an integral part of the broken equation. They had to correct their original certificate to include this override host in the certificates SAN field
3. Run Flipt

### Expected Behavior

It should be possible to get Flipt running. Flipt should not fail to start with a timeout error.

<sub>[FLI-558](https://linear.app/flipt/issue/FLI-558/investigate-https-support)</sub>

**Comment by GeorgeMac** [comment]
As soon as I wrote this issue I started to become suspicious of the `host` field:
https://github.com/flipt-io/flipt/blob/main/cmd/flipt/main.go#L412

I have a feeling if you use a hostname (that is not the loopback `localhost`) here that the gateway client is not going to be able to dial the grpc server.

**Comment by markphelps** [comment]
> One way to remedy this might be to have the gRPC server start a second listener for the gateway client to use.

We discussed this today and think this might be the way to do it

**Comment by markphelps** [comment]
Closing as resolved per Discord: [https://discord.com/channels/960634591000014878/1123489431249236038/1146191587198648410](https://discord.com/channels/960634591000014878/1123489431249236038/1146191587198648410)
