### ISSUE TITLE
Variant distribution

### ISSUE THREAD

**Issue by satishviswanathan** [flipt-io/flipt#1981]
Version : v1.24.2

Flag

![image](https://github.com/flipt-io/flipt/assets/17437409/fc79faf9-381f-4dc0-a009-186f835fb458)

Evaluation
![image](https://github.com/flipt-io/flipt/assets/17437409/44822d1c-80eb-4de2-b426-0c89f5fd5a61)

In the console when I try to evaluate the flag using the context it always returns a single variant "dark"

**Comment by markphelps** [comment]
Hey @satishviswanathan , what context and entity ID are you using to evaluate in the console?

Have you tried varying the context values? also what are the constraints for the `gold-account` segment if any?

**Comment by markphelps** [comment]
The evaluation response (variant that is chosen) is dependent on both the `EntityID` and the `Context` values.

So if either one of those changes you'll likely (50% change) get a different result. Note the `EntityID` in the console is just a random UUID, but in a real world use case it would likely be something like a `userID`

https://www.flipt.io/docs/concepts#entities

We also recently added a section to our docs that goes into more detail about how the evaluation 'bucketing' and 'stickiness' work https://www.flipt.io/docs/concepts#bucketing
