### ISSUE TITLE
[FLI-212] Implement GitHub OAuth Login

### ISSUE THREAD

**Issue by markphelps** [flipt-io/flipt#2004]
TODO: fill out details, but basically add Oauth login support for GitHub

[https://github.com/flipt-io/flipt/issues/779#issuecomment-1677329682](https://github.com/flipt-io/flipt/issues/779#issuecomment-1677329682)

<sub>From [SyncLinear.com](https://synclinear.com) | [FLI-212](https://linear.app/flipt/issue/FLI-212/implement-github-oauth-login)</sub>

**Comment by GeorgeMac** [comment]
This will be available in the next Minor release (`v1.26.0`)
