### ISSUE TITLE
Return flagKey in evaluation response

### ISSUE THREAD

**Issue by WDaan** [flipt-io/flipt#2006]
### Describe the Bug

When using the new evaluate endpoints, the response no longer returns what flag was evaluated. Only for failed evaluations.

### Version Info

1.24.2

### To Reproduce

Make a call to `/api/v1/namespaces/default/batch-evaluate` and `/evaluate/v1/batch` and notice the different reponses.

### Expected Behavior

The flagKey to be included in the evaluation response.

### Additional Context

I know that you know which flags you requested to be evaluated and you can remap accordingly, yet just including the flagKey in the response makes it just a tad easier.

Let me know what you think & thanks for the great product so far!

**Comment by GeorgeMac** [comment]
Hey @WDaan 👋 

Just going to relay this, as we had the same question in Discord recently.
Technically speaking you can request as many different flags as you like in the same batch.
You can also request the same flag multiple times with different contexts.
So including the flag key is not quite enough to correlate it with the original request, you would also need the context.

But if folks still find there is value in having the flag key, then we can certainly put it back 👍

**Comment by WDaan** [comment]
Thanks!

Yes, you're right, you would need the context as well. Good to know that the order is the same, yet this doesn't feel as solid as being able to rely on the response object itself.

Another approach would be to return the `requestId` you passed for your evaluation. That way you only need the 1 identifier instead of the key + context.

**Comment by WDaan** [comment]
I think this problem would be resolved if the requestId would be honored in batch-evaluation. Right now it's always empty?

<img width="1147" alt="Screenshot 2023-09-29 at 10 19 00" src="https://github.com/flipt-io/flipt/assets/25707052/e37a730e-f7f5-45bc-93fe-9a5f9b4b90ad">

**Comment by markphelps** [comment]
Thanks @WDaan this should be released Monday of next week

**Comment by WDaan** [comment]
Awesome! Thanks @markphelps :) keep up the great work
