### ISSUE TITLE
[FLI-579] Monaco web workers dont work

### ISSUE THREAD

**Issue by markphelps** [flipt-io/flipt#2059]
In v1.26+, the background web workers to do syntax highlighting for the new [Monaco editor ](https://microsoft.github.io/monaco-editor/)for the console don't actually start/run, which means no syntax highlighting occurs

See linked PR:
_Originally posted by @markphelps in https://github.com/flipt-io/flipt/pull/2040#discussion_r1304295631_
            

<sub>[FLI-579](https://linear.app/flipt/issue/FLI-579/monaco-web-workers-dont-work)</sub>

**Comment by erka** [comment]
@markphelps please close this one. I learnt why Github doesn't do it automatically and I will create correct PRs in the future.

**Comment by GeorgeMac** [comment]
Nice one @erka 🙌
