### ISSUE TITLE
[FLI-710] Add organization membership check to GitHub authentication method

### ISSUE THREAD

**Issue by GeorgeMac** [flipt-io/flipt#2065]
Originally requested in Discord https://discord.com/channels/960634591000014878/1146699437536727041

We should add a feature to limit who can authenticate using the GitHub authentication method, based on their organization memberships.

One simple approach we could take here is to support a configuration field identifying the desired organization membership (call it `organization` or `member_of` or something).
This would be similar to the `email_matches` property on the OIDC authentication method.

Then we can use the access token retrieved to get the list of organizations the user is a member of (`api.github.com/users/<user>/orgs`). In an authenticated context, this should return the users organizations. Though it _may_ need the additional scope `read:org` (I think team membership definitely needs this, but just listing org membership might be fine with the `read:user` scope).
Once we have their associated orgs, we could ensure that the lists contains the configured organization name.

This would likely require the following changes (for anyone interested in giving this a go):
- List org and enforcement check [here](https://github.com/flipt-io/flipt/blob/main/internal/server/auth/method/github/server.go#L161). This would be conditional, based on whether or not an organization had been configured. Plus unit test.
- New configuration option on [here](https://github.com/flipt-io/flipt/blob/main/internal/config/authentication.go#L423-L430). Probably best to just call it `organization`.
- Updates to both the CUE and JSON Schema to reflect the new configuration option.

<sub>[FLI-710](https://linear.app/flipt/issue/FLI-710/add-organization-membership-check-to-github-authentication-method)</sub>

**Comment by markphelps** [comment]
I like how grafana allows for both `allowed_organizations` and `team_ids`: https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/github/#configure-role-mapping

**Comment by GeorgeMac** [comment]
☝️ Nice. Another way this could be implemented is to require `read:org` and specifically attempt to read the members of the requested `allowed_organizations` and then search for the calling user (plus check teams).
