### ISSUE TITLE
Possible bug in export of segment rank

### ISSUE THREAD

**Issue by ahobson** [flipt-io/flipt#2085]
### Describe the Bug

I'm not 100% positive this is a bug, but it seems like an export removes the `rank` from segment rules. That might be a documentation issue as perhaps that field is no longer supposed to be used? I notice that <https://www.flipt.io/docs/configuration/storage#defining-flag-state> has example YAML from before the boolean/variant separation and I wonder if it should be updated to use an example that includes the `type` ?

### Version Info

```
Version: dev
Commit: ed6b7f05285f8e9d79d2286dc89e155873d83972
Build Date: 2023-08-08T17:25:48Z
Go Version: go1.20.6
```
### To Reproduce

```
# in one window
./bin/flipt
# in another window
./flipt import \
  --address http://localhost:8080 \
  --create-namespace ./internal/storage/fs/fixtures/fswithoutindex/prod/prod.features.yaml
./flipt export \
  --address http://localhost:8080 \
  -n production > prod.yaml
grep -c rank ./internal/storage/fs/fixtures/fswithoutindex/prod/prod.features.yaml prod.yaml
# The output is
# ./internal/storage/fs/fixtures/fswithoutindex/prod/prod.features.yaml:1
# prod.yaml:0
```
### Expected Behavior

Should the rank be exported?

**Comment by GeorgeMac** [comment]
Ahh yes, thanks for pointing this out! This is a missing docs update.
Rank has bee deprecated and isn't exported anymore.
We made the rank implicit to the order in the yaml array.
