### ISSUE TITLE
Auto-Run DB Migrations on Docker Launch

### ISSUE THREAD

**Issue by JGaudette** [flipt-io/flipt#2088]
### Problem
Is your feature request related to a problem? Please describe:

Yes, the problem I'm facing is the absence of an automated mechanism to run database migrations when the Docker container launches. Currently, upgrading to new versions requires manual intervention. This makes the upgrade process cumbersome, especially when deploying in environments that prioritize automation. Without this feature, I find myself constantly monitoring the container, recognizing when it's struggling, and then manually mounting the new image with the database file to run the `flipt --migrate` command.

### Ideal Solution
Describe the solution you'd like:

I would like an enhancement in the Docker image that automatically triggers the flipt --migrate command upon its launch. This will enable seamless upgrades between different versions without any manual steps. By integrating this feature, users can have confidence that database migrations are handled automatically, streamlining deployments and ensuring application stability.

### Additional Context
Add any other context about the feature request here.

The current approach not only introduces potential downtimes due to manual intervention but also poses risks of human error. An automated migration feature will considerably reduce these risks and pave the way for a smoother and more efficient upgrade experience.

It's worth noting that in many modern cloud-native environments, automation is a fundamental principle, and the current manual migration process feels misaligned with such ecosystems.

Thank you so much for considering this feature!

**Comment by GeorgeMac** [comment]
Hey @JGaudette 

Flipt has the flag `--force-migrate` which you can pass on startup to have it attempt migration on startup before it starts the server.

If you're running in Kubernetes via the Helm chart, a user recently contributed a Helm Hook to auto run the migrations via a Job. You simply have to enable the migrations enabled property to true in the values yaml:
https://github.com/flipt-io/helm-charts/blob/main/charts/flipt/values.yaml#L182-L188

Do either of these options work for you?

The force migrate step is disabled by default to encourage operators to manage upgrades manually, given the potential for something to go wrong during migrations. We advise folks to back up their database before migrations. So this default is really an attempt to protect folks from accidental corruption.
We strive to not get in this situation and try to puts in place tests to avoid it. But just an over abundance of caution really.

**Comment by JGaudette** [comment]
Hi @GeorgeMac,

Thank you so much for the response!  I wasn't able to find any documentation about `--force-migrate`, so really appreciate the help, looks like this will work perfectly!

**Comment by markphelps** [comment]
Hey @JGaudette ! I think we 'hid' the force-migrate command but it's probably best that we unhide it and document it, perhaps with a potential warning in our docs. Will get that documentation updated ASAP

**Comment by GeorgeMac** [comment]
Awesome, cheers @JGaudette I will have a look and see if we can put that somewhere appropriate in the docs.
