### ISSUE TITLE
Facing Challenges in Client Node @flipt-io/flipt npm package. 

### ISSUE THREAD

**Issue by susanta96** [flipt-io/flipt#2124]
### Describe the Bug

I am using the latest version of the server & client. However, there are some cors-related errors. although I have set enabled the cors using environment variables.

![image](https://ik.imagekit.io/4gk79wff3ko/plugin-upload/Screenshot_2023-09-16_at_8.45.03_PM_WpLZvT0D4.JPG?tr=h-auto,f-auto)

Still, I am not able to access from my localhost or any other client platform, to use basic bolean evaluate API. I don't have any authentication as of now. 

![client_api_cors](https://ik.imagekit.io/4gk79wff3ko/plugin-upload/Screenshot_2023-09-16_at_8.50.49_PM_WzOCHhJEg.JPG?tr=h-auto,f-auto)

### Version Info

Run `flipt --version` and paste the output here: 1.27.0

### Additional Context

Examples:

- OS - Server Ubuntu Docker
- Config file used -- default, override by env.
- Database used (SQLite, MySQL, Postgres, etc.) - SQLITE

**Comment by GeorgeMac** [comment]
Hey @susanta96! Just to check, did you mention before that you were serving Flipt through nginx? Just want to check the Cors option requests are making their way to Flipt itself.

**Comment by susanta96** [comment]
Yes. Using nginx. But I believe it should making it to flipt. 

http://0.0.0.0:8080

This is working . And mapped as of now:

https://flipt.asdeva.dev

There everything is running. 

But accessing API from different cors having issues. Don't know why. Is it because I am trying with https ??

**Comment by markphelps** [comment]
hi @susanta96 !

Sorry you are having issues getting your app integrated with Flipt. I did a bit of looking and might have found something. 

Do you know if you are serving Flipt over HTTP2? This would likely be setup via your Nginx proxy or your hosting provider.

The reason I ask I that I do not think the Flipt Node SDK will be able to communicate over HTTP which might be why you are having issues.

I modified our [example NextJS](https://github.com/flipt-io/flipt/tree/main/examples/nextjs) app to point to your instance and see the following errors locally:

```
"level":"error","ts":1694896935.109007,"logger":"http.log.error","msg":"http2: Transport: cannot retry err [stream error: stream ID 3; PROTOCOL_ERROR; received from peer] after Request.Body was written; define Request.GetBody to avoid this error","request":{"remote_ip":"172.19.0.1","remote_port":"55402","client_ip":"172.19.0.1","proto":"HTTP/1.1","method":"POST","host":"localhost:8081",
```

This makes me think its an issue with serving the Flipt API over HTTP2 to be consumed by our REST Client (flipt-node).

I also see similar HTTP/2 headers when doing a curl request:

```
workspace/flipt - [main●] » curl -v https://flipt.asdevs.dev/api/v1/flags
*   Trying 194.135.80.4:443...
* Connected to flipt.asdevs.dev (194.135.80.4) port 443 (#0)
* ALPN: offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=flipt.asdevs.dev
*  start date: Sep 16 09:32:57 2023 GMT
*  expire date: Dec 15 09:32:56 2023 GMT
*  subjectAltName: host "flipt.asdevs.dev" matched cert's "flipt.asdevs.dev"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* using HTTP/2
* h2h3 [:method: GET]
* h2h3 [:path: /api/v1/flags]
* h2h3 [:scheme: https]
* h2h3 [:authority: flipt.asdevs.dev]
* h2h3 [user-agent: curl/7.88.1]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x14e012400)
> GET /api/v1/flags HTTP/2
> Host: flipt.asdevs.dev
> user-agent: curl/7.88.1
> accept: */*
>
< HTTP/2 200
< server: openresty
< date: Sat, 16 Sep 2023 20:47:10 GMT
< content-type: application/json
< content-length: 488
< content-security-policy: default-src 'self'; img-src * data:; frame-ancestors 'none';
< grpc-metadata-content-type: application/grpc
< vary: Origin
< x-content-type-options: nosniff
< x-served-by: flipt.asdevs.dev
```

Would it be possible to deploy Flipt using HTTP/1.1 transport instead?

**Comment by susanta96** [comment]
Hi @markphelps, thanks for this observation. However, My Nginx is set up with Http2 support, if the client doesn't support this, it will fall back to HTTP/1.1. Not sure, what to do?

**Comment by susanta96** [comment]
This is the issue with the node package itself. Fetch API is working smoothly. @markphelps @GeorgeMac Thanks both of you for helping. 

I would try to look into the package more.

**Comment by markphelps** [comment]
Hey @susanta96 , I think the reasoning behind the failure with http2 from our [flipt-node](https://github.com/axios/axios/issues/1175) client is that the client uses axios under the hood which [doesn't seem to support http2](https://github.com/axios/axios/issues/1175)

Our node client is actually generated using [fern](https://github.com/fern-api/fern-typescript), so we have limited control over how it works. But I did find that we can allow end users to configure a [custom fetcher](https://github.com/fern-api/fern-typescript#-allowcustomfetcher) so maybe that's something we can explore in the next release of our SDK?

**Comment by susanta96** [comment]
Sure, that's actually a good idea, I will also check the node-package more, and if possible give PR as well. Let's see.
