### ISSUE TITLE
AzureAD SSO Support

### ISSUE THREAD

**Issue by look4regev** [flipt-io/flipt#2179]
### Problem

It seems the project supports only oAuth2.0 without AzureAD. What about SAML SSO based on AzureAD? As many companies use AzureAD, it'll be a major enabler to support SSO with AzureAD. 

### Ideal Solution

Support Enterprise AzureAD SSO authentication to the tool so developers can access the UI for their use when it is deployed internally.

### Search

- [X] I searched for other open and closed issues before opening this

**Comment by WDaan** [comment]
I use Azure AD SSO, works just fine. Out of curiosity particular reason why you need SAML?

**Comment by look4regev** [comment]
Thanks @WDaan, good to know it has been tested with AzureAD. No, actually there is no reason to use SAML instead of OIDC. We can close this issue, though what do you think about adding AzureAD to the list of verified OIDC providers in the docs?

https://www.flipt.io/docs/configuration/authentication
![image](https://github.com/flipt-io/flipt/assets/4006829/48366413-821c-4556-bcf1-a0dcf180ef08)

**Comment by markphelps** [comment]
Will add AzureAD to the docs @look4regev ! Good idea!

And thanks @WDaan for confirming!

**Comment by markphelps** [comment]
Updated docs! Closing for now. Thanks again!
