### ISSUE TITLE
[FLI-632] User Info in UI

### ISSUE THREAD

**Issue by WDaan** [flipt-io/flipt#2222]
### Problem

When you log in using SSO you get a blank user with a logout button. It would look more comple if the user name or email would be shown.

### Ideal Solution

<img width="224" alt="Screenshot 2023-10-11 at 09 12 20" src="https://github.com/flipt-io/flipt/assets/25707052/27414934-2359-4be5-9fa4-25836e4ed82b">

Show some user info in the top right corner.

### Search

- [X] I searched for other open and closed issues before opening this

<sub>[FLI-632](https://linear.app/flipt/issue/FLI-632/user-info-in-ui)</sub>

**Comment by atifcppprogrammer** [comment]
Hi there @markphelps ! I'm willing to work on this, please assign this issue to me :+1:.

**Comment by markphelps** [comment]
Cheers @atifcppprogrammer , will happily assign to you. Much appreciated 🙏🏻. 

I think we only actually show the name on hover if we get an image url from the oidc provider

https://github.com/flipt-io/flipt/blob/23cb399ac5702f2ef4d7a93f062b8dbef99e2a8d/ui/src/components/header/UserProfile.tsx#L54C1-L68C1

In @WDaan s screenshot it seems there is no user profile image.

I could see us adding a check for the name regardless of if we have the image url and add that on hover. 

It might also be nice to add either the name or email to the menu (that pops up when clicking the user icon or picture) as @WDaan suggested. 

One thing I need to check is if we can be guaranteed to always get either the user name or email from all oidc providers or if we have to ensure we always add the correct scopes before making the request. Will look when at my computer in the morning but wanted to get the convo going.

**Comment by WDaan** [comment]
@atifcppprogrammer it depends on which OIDC provider you're using, for Azure nothing shows up at all. So showing username/email somewhere would be nice. Being always in the top-right corner or on the dropdown when you click the profile, ... just some ideas.

**Comment by atifcppprogrammer** [comment]
Hey @markphelps sorry I got a little bit swamped at work ! I'm going to start working on this, btw just wondering if you were able to make the following :point_down: determination.
> _One thing I need to check is if we can be guaranteed to always get either the user name or email from all oidc providers or if we have to ensure we always add the correct scopes before making the request._

**Comment by atifcppprogrammer** [comment]
Hey @markphelps sorry I got a little bit swamped at work ! I'm going to start working on this, btw just wondering if you were able to make the following :point_down: determination.
> _One thing I need to check is if we can be guaranteed to always get either the user name or email from all oidc providers or if we have to ensure we always add the correct scopes before making the request._

**Comment by GeorgeMac** [comment]
Hey @atifcppprogrammer 👋 
Sadly we cannot guarantee a user name or email. The scopes `profile` or `email` have to be requested explicitly for those to come through. We dont mandate that those scopes get requested in Flipt, that is up to the configurer.

The one thing we can guarantee is the `sub` claim. Which could be any internal identifier for the IdP (could just be an integer ID), and we're currently not storing that (but we could).

**Comment by atifcppprogrammer** [comment]
@GeorgeMac so I take it that in the event we have neither the username or email, we can show the value of the `sub` claim ?

**Comment by GeorgeMac** [comment]
@atifcppprogrammer sorry, all I meant was that this is the only thing we can potentially guarantee. But reflecting on it, this will mostly be meaningless for the UI. I think we just have to accept that there can be cases with no email or picture.
