### ISSUE TITLE
[Bug]: Update button in Rule is not working

### ISSUE THREAD

**Issue by satoren** [flipt-io/flipt#2231]
### Bug Description

After changing the Rule of Variant type and pressing the Update button, 
I get a toast saying that I succeeded, but nothing is reflected.

### Version Info

v1.28.1

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

1. create flag as Variant
2. create segment
3. create two variants `a` and `b` in flag
4. add rule as Single Variant with `a`
5. change Variant `a` to `b` and press update button

https://github.com/flipt-io/flipt/assets/11295976/f70c5ea5-d58f-4ead-930e-d93e7a961065

### Expected Behavior

Changes will be reflected

**Comment by GeorgeMac** [comment]
Thanks for bringing this issue in @satoren ! And the video and repro are super helpful. I will dig into this shortly.

**Comment by GeorgeMac** [comment]
Yep, I have replicated it exactly as described. I will dig into this some more.

**Comment by GeorgeMac** [comment]
I have a feeling this big old TODO is related:
https://github.com/flipt-io/flipt/blob/573667589c9c4a682732685d5ad0afdc52ffccb6/ui/src/components/rules/forms/QuickEditRuleForm.tsx#L134-L155

Going to wait for @markphelps @yquansah to come online and perhaps give some backstory.

**Comment by markphelps** [comment]
yeah, i dont think there was any well defined reason why we dont allow this. I just know that on the server side it is checked for and we have a TODO there as well: https://github.com/flipt-io/flipt/blob/main/internal/storage/sql/common/rule.go#L685C1-L685C1

We have an internal issue tracking this (FLI-497). Perhaps is time we just go ahead and fix these TODOs on both the backend and frontend, as its been a while and no reasons why this should be dis-allowed have come to mind.
