### ISSUE TITLE
Support for passing OIDC client secret via environment variable

### ISSUE THREAD

**Issue by jarviliam** [flipt-io/flipt#2233]
### Problem

I would like to setup flipt with OIDC but I'm required to provide the client_secret via the yaml configuration which means I can't really commit the configuration for gitops. To work around this I have to locally build the image with the client_secret yaml, push to a private repository and use the image like that.

### Ideal Solution

Some way of telling Flipt to look for an environment variable for the secret. For example, argocd allows you to specify the oidc client secret in a yaml configuaration like this `clientSecret: ${secret_name}:{key}` where `secret_name` is a Kubernetes secret and `key` is the value in the secret.

Something as simple as `clientSecret: ${ENV_NAME}` would solve it I think but I'm open to any alternative solutions!

Thank you!

### Search

- [X] I searched for other open and closed issues before opening this

**Comment by GeorgeMac** [comment]
Hey @jarviliam 

You can already pass any flipt configuration parameter as environment variables instead.

For this particular parameter the environment key looks like:

FLIPT_AUTHENTICATION_METHODS_OIDC_PROVIDERS_<yourprovidername>_CLIENT_SECRET

This part of the docs describes how to you can turn any configuration key into and env var key. It is just a mapping from one to the other:
https://www.flipt.io/docs/configuration/overview#environment-variables

**Comment by jarviliam** [comment]
Oh wow I completely overlooked this. Thanks for pointing me in the right direction and thanks for your work on flipt!

**Comment by GeorgeMac** [comment]
That’s no worries @jarviliam and thanks for the kind words! Always feel free to open issues any time.

This is an easy one to miss too. I wonder if even the section should at least be hoisted to the top of the page.
Also, sometimes in the other docs pages we have a tab with config and a tab with env var in the example config blocks. I think we could do that some more for the auth docs.
This is good feedback in itself 😄
