### ISSUE TITLE
[FLI-634] gRPC health check

### ISSUE THREAD

**Issue by zunhaowei** [flipt-io/flipt#2234]
### Problem

We setup flipt server in k8s and call flipt server through gRPC. In flipt's k8s pod, we implemented liveness and readiness probes using [flipt's HTTP health check endpoint](https://github.com/flipt-io/flipt/blob/573667589c9c4a682732685d5ad0afdc52ffccb6/internal/cmd/http.go#L98). 

This is suboptimal for us because we call flipt via gRPC instead of REST, and flipt's gRPC server and REST server are listening to different ports.

### Ideal Solution

flipt may provide a [gRPC health check API](https://grpc.io/docs/guides/health-checking/).

### Search

- [X] I searched for other open and closed issues before opening this

### Additional Context

Slack message from [george@flipt.io](mailto:george@flipt.io)

> No I think it is fair to say that it doesn’t actually probe the state of the grpc listener. It will only tell you that the http server is ready to handle requests. I think technically speaking the gRPC server might not be ready at that point.

> We could definitely update it though to go through the gRPC stack. As you say, implement it as a gRPC health check handler would be better. We could then plumb the HTTP health endpoint to go through our gRPC gateway too then. That would be more representative.

> Would you be open to creating an issue for this on the repo? We can look to getting that in ASAP.

> Aside: We could also go further and add in things like connection state for database, cache etc. Though I know this can get hairy in k8s and lead to cascading failures if you’re not careful. Maybe we could make that opt in and configurable between probe types (health vs ready and so on).

<sub>[FLI-634](https://linear.app/flipt/issue/FLI-634/grpc-health-check)</sub>

**Comment by markphelps** [comment]
note to self: we should add healthchecks documentation to our docs for both HTTP and GRPC
