### ISSUE TITLE
Deploy to Podman or Docker

### ISSUE THREAD

**Issue by mmm8955405** [flipt-io/flipt#2250]
### Problem

Any documentation about deploying to Podman or Docker?

### Ideal Solution

Deploy to Podman or Docker. Not just k8s

### Search

- [X] I searched for other open and closed issues before opening this

**Comment by GeorgeMac** [comment]
Hey @mmm8955405 

We have a section in our docs on getting Flipt running with Docker. Does this help with your needs?
https://www.flipt.io/docs/installation#docker

Granted it is not a guide like we have for Kubernetes. But it should help get going with Docker.

**Comment by mmm8955405** [comment]
> Hey @mmm8955405
> 
> We have a section in our docs on getting Flipt running with Docker. Does this help with your needs? https://www.flipt.io/docs/installation#docker
> 
> Granted it is not a guide like we have for Kubernetes. But it should help get going with Docker.

Not installing flip. I have written a Java application program on how to deploy it to a remote VPS Docker environment

**Comment by GeorgeMac** [comment]
We can definitely put a more guide oriented documentation page up which is similar to the k8s and fly pages. Though there probably wouldn’t be much more detail in this, compared with what we have in the docker section of the installation page.

The installation page I linked there has a couple examples of docker run commands in it. Do you have any more requirements than just the docker run command syntax and how to pass in flipt configuration via docker?

**Comment by mmm8955405** [comment]
> We can definitely put a more guide oriented documentation page up which is similar to the k8s and fly pages. Though there probably wouldn’t be much more detail in this, compared with what we have in the docker section of the installation page.
> 
> The installation page I linked there has a couple examples of docker run commands in it. Do you have any more requirements than just the docker run command syntax and how to pass in flipt configuration via docker?

I think you completely misunderstood my meaning. What you said is all about how to install the Flipt program on different platforms. What I mean is, I wrote a Java or PHP program, how can I deploy Java or PHP programs to remote VPS through Flip

**Comment by GeorgeMac** [comment]
We could definitely do a guide to Podman (I am not familiar with it, but I am sure we can figure that out).
I was just curious what was missing details for Docker in particular.

**Comment by GeorgeMac** [comment]
> > We can definitely put a more guide oriented documentation page up which is similar to the k8s and fly pages. Though there probably wouldn’t be much more detail in this, compared with what we have in the docker section of the installation page.
> > The installation page I linked there has a couple examples of docker run commands in it. Do you have any more requirements than just the docker run command syntax and how to pass in flipt configuration via docker?
> 
> I think you completely misunderstood my meaning. What you said is all about how to install the Flipt program on different platforms. What I mean is, I wrote a Java or PHP program, how can I deploy Java or PHP programs to remote VPS through Flip

Ah, that definitely explains the confusion a bit more.
Both of our guides for Kubernetes and Fly.io are about deploying _Flipt_ to those platforms.
They're not about how you deploy your own applications to those platforms.

How you choose you deploy your applications to these kinds of hosting environments is a bit out of scope for Flipt's documentation. I would refer to those platforms own documentation for deploying there.

That said, perhaps our labs repository might be more helpful here: https://github.com/flipt-io/labs/tree/main/chatbot
Here we have a more end to end example of connecting an application deployed via Docker compose with Flipt running alongside. We could always look to getting more examples like this together for our guides. Is that more what you had in mind?

**Comment by GeorgeMac** [comment]
I hope that didn't read as dissmissive @mmm8955405. We would love to understand how we can help here with Flipt and your needs. We can definitely discuss getting guides together that are more end to end with example applications configured alongside Flipt in different deployment environments. If that is more what you're looking for of course.

**Comment by mmm8955405** [comment]
> I hope that didn't read as dissmissive @mmm8955405. We would love to understand how we can help here with Flipt and your needs. We can definitely discuss getting guides together that are more end to end with example applications configured alongside Flipt in different deployment environments. If that is more what you're looking for of course.

I think it was my mistake. I believe that Flip can perform functions in the field of CI/CI. So this issue has been closed Good night
