### ISSUE TITLE
[Bug]: Preflight requests 501

### ISSUE THREAD

**Issue by ardyfeb** [flipt-io/flipt#2252]
### Bug Description

`OPTIONS` method implemented for REST API. This is required when evaluating with REST API on user browser

![Screenshot 2023-10-17 at 15 17 30](https://github.com/flipt-io/flipt/assets/30074366/fda1a8a1-d79b-467e-8db3-e8a2344b2875)

### Version Info

v1.24.0

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

- Call evaluate api `/evaluate/v1/boolean`
- Check network request

### Expected Behavior

- Preflight request passed

### Additional Context

- Deployment: Docker
- Database: Default (local)

**Comment by ardyfeb** [comment]
I missed that🫣, thank youu

**Comment by GeorgeMac** [comment]
No worries @ardyfeb 🙌
