### ISSUE TITLE
[FLI-636] `flipt evaluate` CLI subcommand

### ISSUE THREAD

**Issue by GeorgeMac** [flipt-io/flipt#2254]
### Problem

It would be nice to have a quick CLI command for running one (or more) evaluations against the evaluation API.
This would be handy for demoing Flipt capabilities, checking connectivity, experimenting with flag configuration or even, with added telemetry, understanding client and server side latency.

### Ideal Solution

A subcommand on the flipt CLI, which makes an evaluation, with support for all the evaluation parameters.

```console
# perhaps entity is random for each eval unless specified via -e
flipt evaluate -e <entity-id> [... key=value] # where key=value are context key/value pairs

# alternative using a more JSON like syntax for context
flipt evaluate {"key":"value"}
```

Ideally, the response would contain all the evaluate response details.
However, (perhaps behind some verbose flag) it would be nice to get some telemetry or additional response metadata out too. For example, it would be nice to get some client and server side latencies.

Bonus: ability to set it into a polling or watch mode. Mostly so that you can see latency over time, or adjust flag state and watch how it changes live.

e.g. `flipt evaluate -w ...` (for watch)

### Search

- [X] I searched for other open and closed issues before opening this

<sub>[FLI-636](https://linear.app/flipt/issue/FLI-636/flipt-evaluate-cli-subcommand)</sub>

**Comment by AmineRhazzar** [comment]
@GeorgeMac I would love to work on this if no one already is.

**Comment by GeorgeMac** [comment]
@AmineRhazzar 💯 all yours if you have the time 🙏

**Comment by erka** [comment]
@GeorgeMac How do we specify `namespace` and `flag` which should be evaluated?

**Comment by GeorgeMac** [comment]
Mmm yeah good question @erka 

Hows about:

```console
flipt evaluate <flag-key> [-n <namespace>] [-e <entity-id>] [-r <request-id>] [k=v context pairs (or json)]
```

My thinking is flag key is required (totally missed that in my description), but the rest have reasonable known defaults.
Namespace can be empty, which means `"default"`.
Entity ID can be e.g. a randomly generated UUID (or similar uniformly random string).
Request ID can be empty or similarly just a random string like entity.
Context can also be empty, but perhaps makes better sense as an optional argument ? could also be a flag that is passed mutiple times (e.g. `-c key1=val1 -c key2=val2`).
