### ISSUE TITLE
Add pagination to namespaces table

### ISSUE THREAD

**Issue by markphelps** [flipt-io/flipt#2274]
Namespaces table in UI doesn't support pagination. We should add it to support many namespaces, re: [https://github.com/flipt-io/flipt/discussions/1885](https://github.com/flipt-io/flipt/discussions/1885)

<sub>From [SyncLinear.com](https://synclinear.com) | [FLI-639](https://linear.app/flipt/issue/FLI-639/add-pagination-to-namespaces-table)</sub>

**Comment by parthmerchant** [comment]
Hey @markphelps! Happy to take this one on (I've tried to contribute in the past #1178 through Rokt Security).

**Comment by markphelps** [comment]
Hey @parthmerchant that would be awesome! Much appreciated!  

Sorry about the previous issue btw

**Comment by erka** [comment]
this probably could conflict with #2499
