### ISSUE TITLE
[Bug]: INVALID_ARGUMENT: flag type BOOLEAN_FLAG_TYPE invalid

### ISSUE THREAD

**Issue by vishaloures** [flipt-io/flipt#2329]
### Bug Description

Hi,
I used the method rpc Evaluate(EvaluationRequest) returns (EvaluationResponse) {}
(https://github.com/flipt-io/flipt/blob/main/rpc/flipt/flipt.proto#L481)
passed all the necessary parameters there 
get an error INVALID_ARGUMENT: flag type BOOLEAN_FLAG_TYPE invalid

found protos in another file rpc Boolean(EvaluationRequest) returns (BooleanEvaluationResponse) {}
 https://github.com/flipt-io/flipt/blob/main/rpc/flipt/evaluation/evaluation.proto#L83 

I have a feeling that in the first case something is not working as expected by default.
### Version Info

v.1.27.2

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

used the method   rpc Evaluate(EvaluationRequest) returns (EvaluationResponse) {}
(https://github.com/flipt-io/flipt/blob/main/rpc/flipt/flipt.proto#L481)
passed all the necessary parameters there requestId = "123455677"
flagKey = "stories"
entityId = token.person_id
namespaceKey = "finamtrade"
contexMap = mapOf("segment" to "true")

get an error INVALID_ARGUMENT: flag type BOOLEAN_FLAG_TYPE invalid

**Comment by GeorgeMac** [comment]
Hello @vishaloures

Pleasuse the new Evaluation RPC service found here for Boolean type flags:
https://github.com/flipt-io/flipt/blob/3504651b34893321b1aefbe5fe97b27e3ebe432c/rpc/flipt/evaluation/evaluation.proto#L82-L86

What you referenced there is the old evaluation API, which only worked for Variant type flags.

**Comment by vishaloures** [comment]
@GeorgeMac thanks, I thought so :)

**Comment by GeorgeMac** [comment]
We could definitely do more to make that clearer. I will look into marking the old API deprecated at the protocol level.
Thanks for raising this @vishaloures 🙏

**Comment by vishaloures** [comment]
@GeorgeMac Hi, when I try use new API, I get an error when compiling "EvaluationServiceCoroutineGrpc.kt: (130, 13): 'boolean' overrides nothing" , because "Boolean" keyword in many programming languages, it is advisable not to use it explicitly. Is it possible to rename a method like GetBoolean ? 🙏🙏🙏🙏

**Comment by GeorgeMac** [comment]
Hey @vishaloures ! Sorry for this! Totally didnt forsee that. We're putting our heads together to have a think how we can fix this without breaking backwards compat for everyone else.
