### ISSUE TITLE
Show rollout description next to rollout title

### ISSUE THREAD

**Issue by phenax** [flipt-io/flipt#2364]
### Problem

Currently the title on the rollout only shows the rollout type. In more complex situations, it can be difficult to understand how the flag is being evaluated.

### Ideal Solution

It would be great to have the rollout description (which is currently available an optional field) being shown next to the rollout title.

### Search

- [X] I searched for other open and closed issues before opening this

**Comment by markphelps** [comment]
Will go out in next release early next week

**Comment by phenax** [comment]
That was quick! Thanks!
