### ISSUE TITLE
[Bug]: Git storage backend seems to fail for repos with submodules

### ISSUE THREAD

**Issue by jalaziz** [flipt-io/flipt#2385]
### Bug Description

While trying to use flipt with the `git` storage backend with a repo that uses submodules, we see the following error:
```
Error: Open path/to/submodule-parent-dir: object not found
```

The error points to a parent directory that contains only submodules.

### Version Info

v1.30.1

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

1.  Configure flipt to use the `git` storage backend pointed to a repo that contains submodules
2. Launch flipt with the configuration

### Expected Behavior

Submodules should be ignored or an option should be provided to

**Comment by GeorgeMac** [comment]
Thanks @jalaziz 🙌 I will look into the dials and levers on go-git to get this supported today.

**Comment by jalaziz** [comment]
Here's a trivial repo that reproduces the issue: https://github.com/jalaziz/flipt-gitops-test

**Comment by GeorgeMac** [comment]
Thanks for the repro repo @jalaziz 
I forked it and pushed up a change with the failing test case in it here https://github.com/flipt-io/flipt/compare/gm/gitfs-submodule?expand=1
Just working on the fix now. I think it is just a case of walking over tree entries that say they're submodules and ignoring them for now. We could add (optional) recursive submodules descent in the future, but will ignore for now.

**Comment by GeorgeMac** [comment]
It is a PR now ☝️

**Comment by GeorgeMac** [comment]
This is currently in `main` but not released. It will be targetted for `v1.31.1`.

**Comment by GeorgeMac** [comment]
`v1.31.1` is out with the fix. Helm chart `v0.46.2` 👍

**Comment by jalaziz** [comment]
Thank you!!
