### ISSUE TITLE
Add support for fixed host keys to Git SSH-key auth method

### ISSUE THREAD

**Issue by jalaziz** [flipt-io/flipt#2386]
### Problem

Ignoring host key verification is not idea. While the docs do warn against `insecure_ignore_host_key`, it is somewhat inconvenient to correctly setup `~/.ssh/known_hosts` on `flipt` containers deployed on Kubernetes via the Helm Chart.

### Ideal Solution

Given that GitHub [publishes their SSH host keys](https://api.github.com/meta), it may actually be easier to allow hardcoding the host key using `ssh.FixedHostKey` or a similar `HostKeyCallback` when used with `go-git`.

Another option could simply be making it easier to pass the correct `known_hosts` file via the `SSH_KNOWN_HOSTS` env var and a `ConfigMap` mounted file when using the helm chart.

### Search

- [X] I searched for other open and closed issues before opening this

**Comment by GeorgeMac** [comment]
I just checked @jalaziz and by default we're using the following HostKeyCallback (go-git does this automatically):
https://pkg.go.dev/github.com/go-git/go-git/v5@v5.10.0/plumbing/transport/ssh#NewKnownHostsCallback

This actually already reads `SSH_KNOWN_HOSTS` and so maybe this is just a case of testing that / documenting it for future users to leverage.

We could still add fixed known hosts too if that is desirable. Seems totally reasonable.

**Comment by GeorgeMac** [comment]
I think I misread that you were asking for `SSH_KNOWN_HOSTS` support there, but I think you're saying that maybe the helm chart should be updated to support making providing that easier?

**Comment by GeorgeMac** [comment]
Opened up a PR on the Helm charts to try and address this https://github.com/flipt-io/helm-charts/pull/111

**Comment by jalaziz** [comment]
> but I think you're saying that maybe the helm chart should be updated to support making providing that easier?

Sorry for the delayed response.

Apologies for the confusion. I was saying that either:

1. Support for using the `FixedHostKey` callback should be added to `flipt` via a config option. OR
2. The helm chart should be updated to make it easier to specify.

Thanks for the quick turnaround on this 🙏🏼

**Comment by markphelps** [comment]
Thanks @jalaziz for raising the issue! Just wanted to confirm that the helm chart update above fixes it for you?

**Comment by jalaziz** [comment]
@markphelps there was an issue in the chart (I've put up a PR [here](https://github.com/flipt-io/helm-charts/pull/113), but I am able to confirm that everything works as expected with the fix.
