### ISSUE TITLE
[Bug]: Git submodule regression in 1.31.2

### ISSUE THREAD

**Issue by jalaziz** [flipt-io/flipt#2429]
### Bug Description

Not entirely sure how this happened, but Git submodules are broken again in v1.31.2.

### Version Info

v1.31.2

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

Deploy flipt v1.31.2 via helm chart version v0.46.3.

**Comment by GeorgeMac** [comment]
Apologies @jalaziz I think a bit of a git slipup happened on that release.

**Comment by GeorgeMac** [comment]
Hopefully 🤞 this is fixed again in the latest `v1.31.3` release.
