### ISSUE TITLE
Move Rollouts to use Redux storage

### ISSUE THREAD

**Issue by markphelps** [flipt-io/flipt#2434]
Re: FLI-650

We'd like to use Redux as the storage abstraction in the UI.

As per https://github.com/flipt-io/flipt/pull/2301, we need to update Rollouts resources in the UI to work through Redux.

**Comment by erka** [comment]
I'll work on it

**Comment by erka** [comment]
I think I've completed this but I don't want to open the PR as there will be a merge conflict with #2461. I will wait until that PR is merged.
