### ISSUE TITLE
[Bug]: Auth token deletion during search may show empty table without search input

### ISSUE THREAD

**Issue by erka** [flipt-io/flipt#2436]
### Bug Description

If user wants to delete the specific auth token and uses search, user will not see the search input or any other tokens. User has to update the page to see other tokens.

### Version Info

v1.31.3

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

The attachment shows the steps 

https://github.com/flipt-io/flipt/assets/19472/7580f509-12c1-45ae-a98d-15b56a6bac31

**Comment by markphelps** [comment]
Thanks for reporting @erka ! Def a bug

**Comment by erka** [comment]
Fix for this could be not to hide the `Searchbox` in `TokenTable.tsx` if there is some text in the search input.

```
      {(tokens.length >= searchThreshold || filter != '') && (
        <Searchbox className="mb-6" value={filter ?? ''} onChange={setFilter} />
      )}
```

**Comment by erka** [comment]
@markphelps what do you think about it?

**Comment by markphelps** [comment]
@erka I tried the above fix locally:

```
      {(tokens.length >= searchThreshold || filter != '') && (
        <Searchbox className="mb-6" value={filter ?? ''} onChange={setFilter} />
      )}
```

but still seeing weird behaviour after delete. Looks like it clears the search filter? which then makes the searchbar hidden again.

![2023-11-23 08 18 53](https://github.com/flipt-io/flipt/assets/209477/9ac5d376-c835-4699-ab73-5c0f7070df41)

**Comment by erka** [comment]
It looks like the original bug is shown in your video. I don't see any places where the `filter` could be reseted. 

With my fix I do expect to see it like this.

https://github.com/flipt-io/flipt/assets/19472/48ce45a8-3d20-4a3c-a767-9dc28838f739

**Comment by markphelps** [comment]
ah lol. i wasnt running the ui in dev mode, so it was still running what was on `main`. 

want to just open a PR with your fix?

**Comment by erka** [comment]
@markphelps I am if this solution is fine.

**Comment by markphelps** [comment]
Thank you! Yes sorry, this seems great to me
