### ISSUE TITLE
[Bug]: Boolean constraint type asks for value when you edit it

### ISSUE THREAD

**Issue by erka** [flipt-io/flipt#2442]
### Bug Description

This is related to #2389 but when you edit the constraint which should not have value.

### Version Info

v1.31.3

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

https://github.com/flipt-io/flipt/assets/19472/a503cdab-875b-4b44-a329-8ed208317245

**Comment by markphelps** [comment]
thanks for reporting @erka !

**Comment by Sanket-Arekar** [comment]
I would like to work on this issue. Can you Please assign me this issue?

**Comment by markphelps** [comment]
yes please! thanks @Sanket-Arekar !!

**Comment by RohanMishra315** [comment]
Hey @markphelps @erka If no one is working on this , Could I take a look ?

**Comment by markphelps** [comment]
@RohanMishra315 I know @Sanket-Arekar mentioned they would like to work on it. Not sure if they are still interested/able to. 

cc @Sanket-Arekar
