### ISSUE TITLE
[Bug]: Redux `createSelector` usage is incorrect and broken

### ISSUE THREAD

**Issue by markerikson** [flipt-io/flipt#2444]
### Bug Description

This app only has a few uses of `createSelector`, but those uses appear to be very incorrect and broken.  They are creating new references in the input functions, and thus will _never_ memoize correctly.

Some examples:

```ts
export const selectFlag = createSelector(
  [
    (state: RootState, namespaceKey: string, key: string) => {
      const flags = state.flags.flags[namespaceKey];
      if (flags) {
        return flags[key] || ({} as IFlag);
      }

      return {} as IFlag;
    }
  ],
  (flag) => flag
);

export const selectNamespaces = createSelector(
  [
    (state: RootState) =>
      Object.entries(state.namespaces.namespaces).map(
        ([_, value]) => value
      ) as INamespace[]
  ],
  (namespaces) => namespaces
);

export const selectCurrentNamespace = createSelector(
  [
    (state: RootState) => {
      if (state.namespaces.namespaces[state.namespaces.currentNamespace]) {
        return state.namespaces.namespaces[state.namespaces.currentNamespace];
      }
      return { key: 'default', name: 'Default', description: '' } as INamespace;
    }
  ],
  (currentNamespace) => currentNamespace
);
```

Any time you have a result function that is `x => x`, you're almost definitely using `createSelector` wrong.

These need to be rewritten to extract relevant values in the input functions, and only calculate the new references in the result function.  For example:

```ts
export const selectNamespaces = createSelector(
  [
    (state: RootState) => state.namespaces.namespaces,
  ],
  (namespaces) => {
    return Object.entries(state.namespaces.namespaces).map(
        ([_, value]) => value
      ) as INamespace[]
  }
);
```

Please see the Redux docs on selector usage and the Reselect docs for more details:

- https://redux.js.org/usage/deriving-data-selectors
- https://github.com/reduxjs/reselect

FWIW, we're about to ship Redux Toolkit 2.0 + Reselect 5.0.  In 5.0, `createSelector` will double-run selectors in development to catch this sort of problem, and would warn about this mistake.

### Version Info

N/A

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

Source code issue, not a runtime issue.

### Expected Behavior

Selectors would be written to correctly memoize results.

**Comment by markphelps** [comment]
Thank you @markerikson !! Will get this fixed before the next release. Really appreciate you opening this!

**Comment by markerikson** [comment]
You're welcome :)  

FYI we're about to ship RTK 2.0 hopefully this week, and I'm debating a couple last-minute changes to Reselect's default memoization behavior.  Been doing some searching for real-world uses of RTK, selectors, etc, and just happened to run across this.
