### ISSUE TITLE
UI: Move Namespaces to use RTK

### ISSUE THREAD

**Issue by markphelps** [flipt-io/flipt#2447]
Like in #2441 

Should try to move namespaces over from using the existing state management with dispatch, asyncThunks, etc to using RTK

https://redux-toolkit.js.org/rtk-query/overview

**Comment by erka** [comment]
@markphelps will you do it? Or can I do it?

**Comment by markphelps** [comment]
yah i wont be able to get to it until next week, so if you are available/interested that would be great!
