### ISSUE TITLE
[Bug]:  Page api call could finish earlier that Layout api calls

### ISSUE THREAD

**Issue by erka** [flipt-io/flipt#2479]
### Bug Description

When you load some flag or segment page using direct url for non-default namespace the error message could appear that resource is not found. It happens because page api call is called before the api requests is completed in `Layout.tsx`. This was a bit less visible before v1.32 because  of `clearError` execution for different api calls. In 1.31.2 you could see that the error popup appears for a second.

### Version Info

 v1.32

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

- create a new namespace
- create a flag/segment that doesn't exist in the default namespace
- force reload the new flag/segment page for non-default namespace

How it looks in v1.32

https://github.com/flipt-io/flipt/assets/19472/927fbdf2-d356-4314-8d78-73a6d995b8eb

How it looks in v1.31.2

https://github.com/flipt-io/flipt/assets/19472/6782962d-2d83-4dc7-850e-c82cb177726c

**Comment by julesglad** [comment]
I would like to work on this, could this be assigned to me? Thanks!

**Comment by markphelps** [comment]
We had to get this bug fix out as it seems to be more severe than what was initially reported

**Comment by julesglad** [comment]
@markphelps I will keep my eyes out for new UI issues, I'd still love to take a look. :)

**Comment by erka** [comment]
> 00% sure how to reproduce it consistently. But it seems as if you haven't selected any namespace from the drop down, you can get in this weird st

@markphelps could you please create a bug for this.

**Comment by markphelps** [comment]
> > 00% sure how to reproduce it consistently. But it seems as if you haven't selected any namespace from the drop down, you can get in this weird st
> 
> 
> 
> @markphelps could you please create a bug for this. 

I think your pr might have fixed this.
