### ISSUE TITLE
[FLI-734] Proposal(Auth): Support JWTs

### ISSUE THREAD

**Issue by markphelps** [flipt-io/flipt#2511]
Support externally created JWTs, verifying via these methods:

* PEM-encoded key file
* JSON Web Key Set (JWKS) in a local file
* JWKS provided by the configured JWKS endpoint

Need to flesh this out a bit more, but here are some good references to get started:

* [https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/jwt/](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/jwt/)
* [https://auth0.com/docs/secure/tokens/json-web-tokens/json-web-key-sets](https://auth0.com/docs/secure/tokens/json-web-tokens/json-web-key-sets)

<sub>From [SyncLinear.com](https://synclinear.com) | [FLI-734](https://linear.app/flipt/issue/FLI-734/proposalauth-support-jwts)</sub>

**Comment by GeorgeMac** [comment]
Implementation note: I think this authentication method should differ from the others, in that it shouldn’t also then cause a flipt client token to be created.

This new method should just always validate the jwt in the auth middleware, like how we lookup client tokens. This will allow the authentication method to remain distributed and not necessarily cause Flipt to require a database.
