### ISSUE TITLE
Button color update for more contrast from disabled state

### ISSUE THREAD

**Issue by julesglad** [flipt-io/flipt#2544]
### Problem

Button colors can cause confusion for users because of how close the disabled and normal state colors are.

Current colors: 
Disabled - bg-violet-300
Normal - bg-violet-400
Hover - bg-violet-500

### Ideal Solution

This button configuration would allow for more contrast between disabled and normal.

Disabled - bg-violet-300
Normal - bg-violet-500
Hover - bg-violet-400

### Search

- [X] I searched for other open and closed issues before opening this

**Comment by julesglad** [comment]
Please assign this issue to me. :)

**Comment by markphelps** [comment]
Thanks for reporting! I've struggled in the past with what makes sense for these states. I like your suggestions
