### ISSUE TITLE
[FLI-748] Auth(OIDC/OAuth): Support AuthStyle config

### ISSUE THREAD

**Issue by markphelps** [flipt-io/flipt#2571]
### Problem

From discord: [https://discord.com/channels/960634591000014878/1186939322411274280](https://discord.com/channels/960634591000014878/1186939322411274280)

> Can we config AuthStyle to send client ID/Secret in Headers when exchange token in OIDC Authentication method (custom provider)

> .. it is in authorization code flow. So my custom provider receive Basic Auth client credentials (not in request body). Which I saw that in go/x/oauth2 library we can set AuthStyle, but I think flipt can not customize this

> More detail, the steps are:

1. Go to my self-hosted flipt website
2. Signin with my custom provider
3. Redirect to custom provider's authen page
4. Authorized and callback to callback url (.../oidc/{provider}/callback like in flipt doc)
5. Flipt server request to exchange token with auth code received from step 3
6. From step 4, it request with client credential in POST body (From what I debug), but my custom provider received it via BasicAuth Header

The issue is at step 6

### Ideal Solution

![image](https://uploads.linear.app/d3f9d655-7ab0-49e9-ade8-b59504819c07/f71d98f3-47d5-4cc6-8525-13a8c79462ba/00b121c6-0cf8-4c9f-94b9-8b3a4c635540?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2QzZjlkNjU1LTdhYjAtNDllOS1hZGU4LWI1OTUwNDgxOWMwNy9mNzFkOThmMy00N2Q1LTRjYzYtODUyNS0xM2E4Yzc5NDYyYmEvMDBiMTIxYzYtMGNmOC00YzlmLTk0YjktOGIzYTRjNjM1NTQwIiwiaWF0IjoxNzAzODczMDI3LCJleHAiOjE3MDM5NTk0Mjd9.wr_ZQSt1-ZV88AokClc_bjVxGTIbbKGROOZ6vJSpDDQ)

Allow configuration of a supported auth style from oauth/oidc lib

### Search

- [X] I searched for other open and closed issues before opening this

### Additional Context

*No response*

<sub>From [SyncLinear.com](https://synclinear.com) | [FLI-748](https://linear.app/flipt/issue/FLI-748/authoidcoauth-support-authstyle-config)</sub>

**Comment by souradeepmajumdar05** [comment]
@markphelps can you attach steps to replicate this, would like to take this up
changes should be around [auth_grpc.pb.go#L472](https://github.com/flipt-io/flipt/blob/main/rpc/flipt/auth/auth_grpc.pb.go#L472)

**Comment by markphelps** [comment]
Hey @souradeepmajumdar05 !! 

So im trying to see if this is something that is possible for us to 'fix', as it seems like it should be working looking through our code as well as the underlying libraries.

Here's what I've found so far:

1. It starts here at the OIDC callback handler where the provider successfully calls back to Flipt to initiate the code/token exchange: https://github.com/flipt-io/flipt/blob/ee2e72791dc8d92114dc9e46d986364992c5c227/internal/server/auth/method/oidc/server.go#L131
2. We get the configured provider and initiate the exchange
3. It calls the [Hashicorp Cap OIDC](https://github.com/hashicorp/cap) provider exchange method: https://github.com/hashicorp/cap/blob/1d58e0e8bd5f948b9d2bebe8b25a81eb0288fe32/oidc/provider.go#L261
4. This eventually calls the underlying oauth2.Exchange method here: https://github.com/golang/oauth2/blob/6e9ec9323da7adcd2cc6e62e4deb9fae4c309a1a/oauth2.go#L223
5. This calls `retrieveToken`: https://github.com/golang/oauth2/blob/6e9ec9323da7adcd2cc6e62e4deb9fae4c309a1a/token.go#L166
6. Which calls `internal.RetrieveToken`: https://github.com/golang/oauth2/blob/6e9ec9323da7adcd2cc6e62e4deb9fae4c309a1a/internal/token.go#L212
7. Which gets down here: https://github.com/golang/oauth2/blob/6e9ec9323da7adcd2cc6e62e4deb9fae4c309a1a/internal/token.go#L212

Looking at this logic, it should actually try both ways (Auth in header first, then Auth in body) and cache the result for the provider for future calls.

And since we don't currently expose setting the `AuthStyle` at all in Flipt, it should use the default 0 value, which according to the code is AutoDetect: https://github.com/golang/oauth2/blob/master/oauth2.go#L85

This should mean that Flipt essentially tries both ways to exchange the code, first in the header as requested per this issue, then in the body.. unless we are using an outdated version of the `oauth2` dependency..

Let me dive in some more and check

**Comment by markphelps** [comment]
```
go list -m all | grep x/oauth2
golang.org/x/oauth2 v0.15.0
```

which is the latest version: https://pkg.go.dev/golang.org/x/oauth2 which should contain the code/perform as described above

https://cs.opensource.google/go/x/oauth2/+/refs/tags/v0.15.0:internal/token.go;l=212

Gonna ask the OP in Discord to help debug this one
