### ISSUE TITLE
Adding a security policy to the projects

### ISSUE THREAD

**Issue by erka** [flipt-io/flipt#2575]
### Problem

There is no clear way to report about any vulnerabilities in private way.

### Ideal Solution

[Github suggests](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) to have this policy in `SECURITY.md` which will explain what to do for the community.  

### Search

- [X] I searched for other open and closed issues before opening this

**Comment by markphelps** [comment]
Added org wide: https://github.com/flipt-io/.github/blob/main/SECURITY.md

Thanks for reporting!
