### ISSUE TITLE
Allow Flipt Dockerfile to use 80 and 443

### ISSUE THREAD

**Issue by cbelsole** [flipt-io/flipt#2593]
### Problem

The Flipt user in the Dockerfile does not have privileges to bind port 80 or 443. As part of an audit, this was a requirement.

Here is the error I got when I tried to use 80 as the server HTTP port:
```
{"L":"FATAL","T":"2023-12-27T23:38:30Z","M":"flipt","error":"http server: listen tcp 0.0.0.0:80: bind: permission denied"}
```

### Ideal Solution

Adding this line after creating the user in the dockerfile fixes the issue.

```dockerfile
RUN apk add libcap && setcap 'cap_net_bind_service=+ep' /flipt
```

### Search

- [X] I searched for other open and closed issues before opening this

**Comment by GeorgeMac** [comment]
I’m sure that we could elevate the capabilities there for the Flipt user. Seems harmless enough.

For my own curiosity, do you know the rationale for this requirement in your audit @cbelsole ? I’m wondering why the need for privilege port binding in the container itself. In my experience that binding to these ports usually happens outside the container (on host or via some lb/mesh) and then it is forwarded to the containers on some higher port, allowing the code inside the containers be run with lower privileges. I assume this is why this also something disabled by default.

That said, this does seem pretty harmless for Flipt to allow, just curious 😄

**Comment by markphelps** [comment]
I was just doing some 👀 myself! Found https://qqq.ninja/blog/post/docker-images-without-root/

My concern is that adding this change might trigger some red flags in other audits if we add this capability if that make sense. IE a simple audit check that looks for `cap_net_bind_service` in the image def. Not sure this is an actual thing though..

**Comment by cbelsole** [comment]
We deploy via AWS Elastic Container service using the network mode `awsvpc`. So we don't have the ability to change the host ports on the container. Since the security groups that allow port traffic are on the ECS services themselves, they have to correspond with the container port. Here is an [AWS doc](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_PortMapping.html) explaining in more detail.

This specific requirement was to only have ports 80 and 443 open to the internet as part of a SOC-2 audit. Thinking more about it, we have our services behind an Application Load Balancer which is the only thing exposed to the internet. We can probably get by without this change.

If you [exposed your ECS services](https://docs.aws.amazon.com/AmazonECS/latest/bestpracticesguide/networking-outbound.html) directly to the public internet this would be a requirement.

**Comment by cbelsole** [comment]
Further reading, AWS [requires you to have a public IP for pulling secrets from the parameter store](https://repost.aws/knowledge-center/ecs-unable-to-pull-secrets) and images from the elastic container registry. This can probably be mitigated by putting everything on a private subnet inside your VPC, but until that's up and running we'd need to run our services on port 80 to be compliant.

**Comment by cbelsole** [comment]
There may be another solution here by running Flipt with [autobind](https://superuser.com/questions/710253/allow-non-root-process-to-bind-to-port-80-and-443) which would allow it to only have access to the ports via the `$FLIPT_SERVER_HTTP_PORT`, `$FLIPT_SERVER_HTTPS_PORT`, and `$FLIPT_SERVER_GRPC_PORT` respectfully.

**Comment by erka** [comment]
I don't think that AWS requires you to have public ip for ECS services. They have [the check in SecurityHub](https://docs.aws.amazon.com/securityhub/latest/userguide/ecs-controls.html#ecs-2) to prevent this as match as possible.
You could use VPC endpoints to access AWS services without public network. Please read more about VPC endpoint and `PrivateDnsEnabled`.

Running Flipt behind ALB is more safe than exposed it to the public network. You should worry more about the encrypted in transit and encrypted at rest. Flipt with http port to the public will not help you with it and even if you have https you will have to worry about the certificate rotation.  With ALB - make sure that `http` listener only redirect all requests to `https` listener and you use ACM with auto managed renewal. Your auditors should be fine with it.  You could use https://www.ssllabs.com/ssltest/analyze.html to check your ALB.

Even if your auditors have concerns about ports you will have to time to remediate according to your policies or evaluate/accept the risk. 

The goal of SOC2 is to improve your company. Keep that in mind. Your auditors would like to see that issues are not ignored.

**Comment by cbelsole** [comment]
Thanks for the advice @erka. I did a little work for this over the weekend. Private subnets seem to be the way to go here despite the migration carrying its own cost. I am going to close this issue.

**Comment by erka** [comment]
@cbelsole you are welcome. First SOC 2 is overwhelmed by different tasks. Each pillar has own prospective. But you will do it.
