### ISSUE TITLE
Make the project buildable using nix (help needed)

### ISSUE THREAD

**Issue by freezeboy** [flipt-io/flipt#2615]
### Problem

Now you made the project `devenv` compatible for your own development process, I would love to be able to use your tool inside my own `devenv` projects (using the `service` integration).

To make it possible, I need to nixify your app, then it will be trivial to add a (local or upstream) module to `devenv`.

I managed to build the api part, but when I try to add the `ui` part, it fails for two reasons:

* I need to run `go mod tidy` manually, so I guess the `go.sum` is not completely up-to-date? (although I am not an expert on Go modules compilation using `mage`)
* For the frontend, `mage` is running `npm` and nix is not a big fan of uncontrolled network access during the build

### Ideal Solution

I think I will have to split the build into two parts:

* First build the `ui/` folder as a classic TS app and keep the `dist/` folder for later use
* Compile the go app manually and simply give the previous `dist/` folder for the runtime

It also looks like the protobuf process is also done manually in you workflows.

Could you provide me with a simple "script" giving the real different steps needed to build locally a production version of your software please or confirm the steps above should work?

### Search

- [X] I searched for other open and closed issues before opening this

**Comment by freezeboy** [comment]
Update, I managed to bypass the tricky steps from the mage build process, for the record, I built the ui independently, then gave the dist folder to the go app and patched the magefile to disable everything that is related to npm

**Comment by markphelps** [comment]
Hey @freezeboy ! Is there anything we can do to make it easier for others who want to integrate Flipt using service integration with Nix? Would love to know more about your use case as well!
