### ISSUE TITLE
[FLI-788] Docs:  Clearer example for securing management backend

### ISSUE THREAD

**Issue by giddel** [flipt-io/flipt#2643]
### Problem

I want to secure the management UI by our Keycloak. So I set these config:

```
authentication:
  required: true 
  exclude:
    management: false   # looks like I want
    metadata: true
    evaluation: true
  [...]
```

This ended in a redirect loop :-(
By stupid trial and error I found out, that it's necessary to set `metadata: false` too to get it work.

### Ideal Solution

Documentation is more clearer in: [https://www.flipt.io/docs/configuration/authentication#exclusions](https://www.flipt.io/docs/configuration/authentication#exclusions)
It would help to move the first marked section below the picture with the default values to the place of the second marked section.  This avoids the backward reference in text.

![Bildschirmfoto vom 2024-01-11 09-40-30](https://uploads.linear.app/d3f9d655-7ab0-49e9-ade8-b59504819c07/38c4441e-9171-4df7-b374-67f8948e4a49/5bd4598a-5e2a-465e-a90a-f0ed36889f81?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2QzZjlkNjU1LTdhYjAtNDllOS1hZGU4LWI1OTUwNDgxOWMwNy8zOGM0NDQxZS05MTcxLTRkZjctYjM3NC02N2Y4OTQ4ZTRhNDkvNWJkNDU5OGEtNWUyYS00NjVlLWE5MGEtZjBlZDM2ODg5ZjgxIiwiaWF0IjoxNzA1OTM1MjczLCJleHAiOjE3MDYwMjE2NzN9.O7k79fkezc-Tn7jtOpMcrDFK-Hs-cNY0ntxeyaCkMkw)

### Search

- [X] I searched for other open and closed issues before opening this

### Additional Context

*No response*

<sub>From [SyncLinear.com](https://synclinear.com) | [FLI-788](https://linear.app/flipt/issue/FLI-788/docs-clearer-example-for-securing-management-backend)</sub>

**Comment by GeorgeMac** [comment]
Cheers for the issue @giddel !

I think we might need to consider removing the option to disable auth on the metadata sections of the API. Unless we can find a solution to the redirection behavior.

It’s worth us considering removing the ability to make these paths unprotected as I’m unsure if there are any valid use cases for allowing unauthenticated actors to change or read flag state when e.g. other actors need auth to perform an evaluation.

The original motivation for the exclusions was really to support just exposing evaluation without authentication. Maybe we went a bit too far.

I think we’re free to remove this capability too if it has never worked. It’s not going to break anyone’s compatibility.

**Comment by giddel** [comment]
:smile_cat:

**Comment by GeorgeMac** [comment]
We removed the ability for metadata to be excluded in the latest version of Flipt.
It is marked deprecated, but is just a noop lever.
