### ISSUE TITLE
[FLI-767] ClickHouse Integration for Flag Eval Analytics

### ISSUE THREAD

**Issue by markphelps** [flipt-io/flipt#2653]
Related to #2504, we could potentially integrate with ClickHouse for storing flag evaluation requests/results, at least cardinality and latencies, potentially variant / rollout results.

This would allow us to add per flag evaluation metrics as a dashboard in the application, as well as do things like 'dead flag' detection (flags that haven't been evaluated in X period of time.

This would mean however that operators would need to deploy Clickhouse somewhere in their infrastructure.

Opening for feedback/thoughts

See: https://clickhouse.com

<sub>[FLI-767](https://linear.app/flipt/issue/FLI-767/clickhouse-integration-for-flag-eval-analytics)</sub>

**Comment by erka** [comment]
This is an example how people try to use Clickhouse with Prometheus metrics https://github.com/jamessanford/remote-tsdb-clickhouse. The biggest difference is the push method. 
It maybe interesting idea for Flipt as it will allow to abstract the metrics storage and use current Prometheus metrics for analytics. It could be that this may be combined with #2500 to have same ui logic for charts in ui.

**Comment by RohanMishra315** [comment]
Integrating with ClickHouse for storing flag evaluation requests/results can be a good solution for adding per flag evaluation metrics and performing tasks like 'dead flag' detection. ClickHouse is a column-oriented database management system that is designed for high-performance analytics and reporting. It can handle large amounts of data and provide fast query response times.

**Comment by markphelps** [comment]
Marking this as done!
