### ISSUE TITLE
[Bug]: reordering rules or rollouts is not captured by audit logs

### ISSUE THREAD

**Issue by erka** [flipt-io/flipt#2710]
### Bug Description

I don't know if this by design or bug, so I would like discuss this before making changes

### Version Info

v1.36

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

- run Flipt with audit enabled
- create a flag with two rules or rollouts
- reorder rules or rollouts
- observe the audit events

**Comment by markphelps** [comment]
I think it is a bug @erka ! good catch!
