### ISSUE TITLE
[FLI-844] [Bug]:  Tracing OTLP doesn't respect configuration

### ISSUE THREAD

**Issue by piclemx** [flipt-io/flipt#2773]
### Bug Description

https://www.flipt.io/docs/configuration/overview#tracing-otlp
For example, in your company, we are setting the `OTEL_SERVICE_NAME` with more info than just `flipt`.

See https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/#general-sdk-configuration

### Version Info

v1.35.0

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

1. Setting the env var on the container 
2. 

### Expected Behavior

Being able to see the ENV var if the configuration is not supported.

<sub>[FLI-844](https://linear.app/flipt/issue/FLI-844/[bug]-tracing-otlp-doesnt-respect-configuration)</sub>

**Comment by erka** [comment]
Flipt doesn't take envs into account.. It probably should do something like

```
resource.New(ctx,
	resource.WithSchemaURL(semconv.SchemaURL),
	resource.WithAttributes(
		semconv.ServiceNameKey.String("flipt"),
		semconv.ServiceVersionKey.String(info.Version)),
	resource.WithFromEnv(),
)
```
