### ISSUE TITLE
[Bug]: Analytics page gives 501

### ISSUE THREAD

**Issue by WDaan** [flipt-io/flipt#2846]
### Bug Description

Whenever you go to the analytics tab, flipt logs a 501. Triggering loadbalancer alerts. Ideally this should not be a 501.

### Version Info

[v1.38.0](https://github.com/flipt-io/flipt/releases/tag/v1.38.0)

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

Open up the analytics tab without analytics configured.

### Expected Behavior

It shows that it's not enabled (like it does) AND it does not use a 5xx response.

**Comment by yquansah** [comment]
@WDaan Thank you for raising the issue!

I believe we may have a fix for this here: https://github.com/flipt-io/flipt/pull/2847

**Comment by markphelps** [comment]
@WDaan just released [v1.38.1](https://github.com/flipt-io/flipt/releases/tag/v1.38.1) that should hopefully fix this for you! lmk if it doesnt

**Comment by WDaan** [comment]
Awesome work :)
