### ISSUE TITLE
[FLI-915] UI: Copy As Dropdown

### ISSUE THREAD

**Issue by markphelps** [flipt-io/flipt#2863]
### Problem

We currently have a `Copy As Curl` button in the evaluation  console page of the UI

![CleanShot 2024-03-16 at 14 59 00](https://github.com/flipt-io/flipt/assets/209477/4c0c91e6-614c-4944-b96d-cd2aabbf8619)

We now have the ability to also evaluate using the [Flipt CLI](https://www.flipt.io/docs/cli/commands/evaluate)

It would be nice to give the user the ability to copy the command that would allow them to evaluate using the Flipt CLI

### Ideal Solution

Make the current `Copy As Curl` button a button titled `Copy` that opens a dropdown that has two options:

- Curl Request
- Flipt CLI

Clicking the curl request option would do the same thing the `Copy As Curl` button does today, copying the curl commands
Similarly, the `Flipt CLI` option would copy the https://www.flipt.io/docs/cli/commands/evaluate command that the user could paste in their terminal if they have the Flipt CLI installed.

### Search

- [X] I searched for other open and closed issues before opening this

### Additional Context

We could use the [Tailwind UI dropdown component](https://tailwindui.com/components/application-ui/elements/dropdowns#component-f8a14da22f26a67757b19f2fe3ca00ed) for this

We already have the Dropdown component at `ui/src/components/forms/Dropdown.tsx` that may just require minimal styling

<sub>[FLI-915](https://linear.app/flipt/issue/FLI-915/ui-copy-as-dropdown)</sub>

**Comment by Alonsohhl** [comment]
hey I would like to be assigned to this task

**Comment by markphelps** [comment]
Awesome thank you @Alonsohhl ! Very much appreciated

**Comment by KirillPerepelitsa** [comment]
Hey @markphelps 

Does this issue still valid ? 

Can i try to resolve it ?

**Comment by markphelps** [comment]
> Hey @markphelps 
> 
> 
> 
> Does this issue still valid ? 
> 
> 
> 
> Can i try to resolve it ?

It is @KirillPerepelitsa ! I can assign you to it. Thank you!🙏🏻

**Comment by markphelps** [comment]
Fixed in #3154 thanks @kyryl-perepelytsia
