### ISSUE TITLE
[FLI-920] Create JSON schema for flag config

### ISSUE THREAD

**Issue by epahl-atlassian** [flipt-io/flipt#2883]
### Problem

Cue can validate flag config, but is not supported by editors for flag definition validation.

### Ideal Solution

Create and publish a JSON Schema for YAML flag feature files so that it can be validated in user's editors.

### Search

- [X] I searched for other open and closed issues before opening this

<sub>[FLI-920](https://linear.app/flipt/issue/FLI-920/create-json-schema-for-flag-config)</sub>

**Comment by GeorgeMac** [comment]
Great idea @epahl-atlassian 
Shame there is only a JSONScheme to CUE converter and not the other way.
Or I wish that CUE could be integrated into editors too. Either way, I want this!

**Comment by halcyonCorsair** [comment]
If I PR'd a super basic json schema for this (probably only against 1.2), where should it go in the codebase?

**Comment by GeorgeMac** [comment]
Great question, @markphelps maybe its worth getting the new public validation package work done just so that we can put this in there? What do you think?

**Comment by markphelps** [comment]
@GeorgeMac yeah it should be good to go here: https://github.com/flipt-io/flipt/pull/2831

@halcyonCorsair , best place is to probably branch off of that PR ☝🏻  and put it in `/core/validation/flipt.json` (`or flipt.schema.json`) as we are making the `validation` package 'public'

**Comment by markphelps** [comment]
Fixed in #2923
