### ISSUE TITLE
UI assistance for arrays data in constraints

### ISSUE THREAD

**Issue by epahl-atlassian** [flipt-io/flipt#2885]
### Problem

Currently the UI requires users to manually add raw json:
<img width="564" alt="Screenshot 2024-03-21 at 10 29 07 PM" src="https://github.com/flipt-io/flipt/assets/61770799/2a40e6de-cbe6-495a-9670-f0223de2839d">

### Ideal Solution

Either add multiple options in the UI similar to segments:
<img width="1306" alt="Screenshot 2024-03-21 at 10 28 08 PM" src="https://github.com/flipt-io/flipt/assets/61770799/6b116eb7-30f5-4a6e-bfd3-198308a7d5b3">

Or input of raw text followed by a comma might be transformed into an array behind the scenes.
<img width="574" alt="Screenshot 2024-03-21 at 10 35 22 PM" src="https://github.com/flipt-io/flipt/assets/61770799/786ef2c2-cef6-40e5-98aa-c8c5d34693c0">

### Search

- [X] I searched for other open and closed issues before opening this

**Comment by kamblehr** [comment]
@erka is there any possibility to pass ["value1", "value2"] in the context payload of batch evaluation?

`curl --request POST \
  --url https://try.flipt.io/evaluate/v1/batch \
  --header 'Content-Type: application/json' \
  --header 'Accept: application/json' \
  --data '{
  "requests": [
    {
      "context": { "valKey": ["value1", "value2"] },
      "entityId": "<entityid>",
      "flagKey": "<flagkey>",
      "namespaceKey": "<namespacekey>"
    }
  ]
}'`

**Comment by erka** [comment]
Hey @kamblehr. Unfortunately, but no. API spec has strict `map<string, string>` type for request context. Please checkout comments in #2909 for more info.
