### ISSUE TITLE
[Bug]: Copy as curl button generates incorrect url

### ISSUE THREAD

**Issue by epahl-atlassian** [flipt-io/flipt#2888]
### Bug Description

Using `Copy as curl` gives a broken url with a missing slash at the start of the url path.
e.g.
```http://127.0.0.1:8080evaluate/v1/boolean```

### Version Info

1.38.2

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

1. Select a flag
2. Optionally add context etc

Result e.g.
```
curl -X POST -H "Content-Type: application/json" -H "Accept: application/json" -H "Cache-Control: no-store" -d '{"flagKey":"micros-alias-failover-opt-in","entityId":"a1ce6552-2efc-43e2-a3a9-ab1161954afd","context":{"service":"my-service"},"namespaceKey":"default"}' \
  http://127.0.0.1:8080evaluate/v1/boolean
```

### Expected Behavior

Return a curl command with a valid url, e.g. `http://127.0.0.1:8080/evaluate/v1/boolean`

**Comment by markphelps** [comment]
Yah I noticed this earlier this week and fixed it it https://github.com/flipt-io/flipt/pull/2875

Will go out in the next release
