### ISSUE TITLE
[Bug]: Evaluation bug when mixing boolean and other constraints

### ISSUE THREAD

**Issue by epahl-atlassian** [flipt-io/flipt#2910]
### Bug Description

If you create a segment with a boolean and a (string or number) constraint on the same property, evaluation will fail with an error like:
```
error: parsing boolean from "10"
```

[example_export.zip](https://github.com/flipt-io/flipt/files/14768261/example_export.zip)

### Version Info

v1.39.0 (docker)

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

1. Create a segment with a boolean and a (string or number) constraint on the same property.
2. Attach the segment to a flag.
3. Attempt to evaluate the property with a non-boolean value (boolean value will succeed).

### Expected Behavior

A flag with a segment with e.g. ANY_MATCH_TYPE and constraints for boolean, string, number should _successfully_ match against any of them.

### Additional Context

Sample data attached above.

**Comment by GeorgeMac** [comment]
Ah intersting, now you raise it, im kind of surprised no one has tried this sooner. As in, overloading the property type in this way.

The simple approach we could take is to treat property parsing errors as non-match.
Example, we make that error a nil (and in the Rust evalautor too):
https://github.com/flipt-io/flipt/blob/c2c0f7761620a8348be46e2f1a3cedca84577eeb/internal/server/evaluation/legacy_evaluator.go#L426-L429

I guess one open question is how does this effect other scenarios: i.e. is this problematic for `ALL_MATCH_TYPE` match (off the top of my head I think it **is not** problematic, it just means the wrong type doesn't match, which seems reasonable?).

If we do this, we likely want to do it for more than just boolean.
The same thing happens for `number` and `string` for the same reason, we treat parsing property as errors:
<img width="1407" alt="Screenshot 2024-03-27 at 10 58 53" src="https://github.com/flipt-io/flipt/assets/1253326/c410e4fa-d123-45c0-9b7a-4930aafbdb4e">
