### ISSUE TITLE
[FLI-936] [Bug]: Export doesnt capture rollout rule order

### ISSUE THREAD

**Issue by markphelps** [flipt-io/flipt#2914]
### Bug Description

`flipt export` doesn't seem to capture rollout rules in the correct order (if they are reordered)

It's easiest to show in a video I think

https://www.loom.com/share/0497e11bf980465a9658411637e0ed10?sid=02c44972-712a-4c7e-941c-ee5972c9d839

### Version Info

1.39.1

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

1. Create some boolean flag rules
1. Run Flipt export
1. Reorder them
1. Run Flipt export again
1. Notice rule order did not change in export

### Expected Behavior

Rule order is captured correctly in export

<sub>[FLI-936](https://linear.app/flipt/issue/FLI-936/[bug]-export-doesnt-capture-rollout-rule-order)</sub>

**Comment by epahl-atlassian** [comment]
Related to this, for git/local/object storage usage, deterministic ordering of export is important.

**Comment by GeorgeMac** [comment]
I actually can't reproduce this. I am seeing the order change as expected in the output.
The code appears to be correctly sorted by rank too.

**Comment by markphelps** [comment]
Yeah closing this as I was incorrect, it did actually re-order the segment rollout under the threshold rollout..
![Screenshot 2024-03-28 at 09 54 01](https://github.com/flipt-io/flipt/assets/209477/eb5d6b72-0976-4240-abd6-12a81565402c)

Will open a new issue for deterministic ordering of export
