### ISSUE TITLE
Accept a username in Redis configuration

### ISSUE THREAD

**Issue by thepabloaguilar** [flipt-io/flipt#2949]
### Problem

The current configuration doesn't allow us to pass a username when configuring a Redis instance as a cache, this is a problem when comming to Redis version 6.0 (or greater) that's using Redis ACL System! So without the username the connection will be refused.

### Ideal Solution

Accept the `user/username` in the redis configuration

### Search

- [X] I searched for other open and closed issues before opening this

**Comment by markphelps** [comment]
@thepabloaguilar great catch! will add this

**Comment by erka** [comment]
Hey @thepabloaguilar. Do you plan to used it with OCI storage?

**Comment by thepabloaguilar** [comment]
Yes, I do @erka

**Comment by erka** [comment]
@thepabloaguilar https://community.flipt.io/t/cache-and-reference-with-git-backend/14/2

**Comment by thepabloaguilar** [comment]
I don't think I've understood completely @erka, the cache for OCI storage I get it (it's already in memory) but I thought the cache also will be used to cache flags evaluation results! Is my last statement wrong?

**Comment by erka** [comment]
@thepabloaguilar I think it's only used on storage level.

https://github.com/flipt-io/flipt/blob/bc3f7be3db3cd5c09e834f82b396e37f0ef2f1a5/internal/cmd/grpc.go#L193-L201

**Comment by markphelps** [comment]
yeah it caches the data used in the evaluation, but not the evaluation results themselves, as this would likely make the cache grow very large depending on usage patterns.

We could benchmark the results of evaluating using OCI storage with and without cache, but as George said in the linked community discourse, adding cache in front is unlikely to speed it up very much and may make it slower actually because the extra hop for Redis

**Comment by thepabloaguilar** [comment]
Got it @erka and @markphelps, maybe an update to the doc are required to maybe make it more clear to the readers like me 🥲 

When I read the [Storage - Caching](https://docs.flipt.io/configuration/storage#caching) session I thought it'll also cache the evaluations because of this items:
* All flag reads and __evaluation__ requests go through the cache
* __Evaluation__ cache entries are purged after the TTL expires only
