### ISSUE TITLE
UI - Flags view - Indicate if a boolean flag has a rollout set

### ISSUE THREAD

**Issue by alexcardell** [flipt-io/flipt#2981]
### Problem

When on the `Flags` page, a `disabled` status boolean flag may have a rollout attached and be opting some users into the flag. This is different from variant flags, where (I believe) `disabled` means no evaluations will occur. 

For use cases where you are opting a segment in, with the default to false (flag disabled), and you have a lot of flags, I think this would be useful context at a glance

### Ideal Solution

On the flags view, indicate how many rollout rules are set on a flag, regardless of status

### Search

- [X] I searched for other open and closed issues before opening this

**Comment by markphelps** [comment]
@alexcardell I like it! one thing we need to think of is how to make the column work for both variant and boolean flags, like what the name would be and how it might mean different things for variant flags

like would we just show number of `rules` for variant flags?

**Comment by alexcardell** [comment]
`rules` makes sense to me, any indication that a boolean flag is _not quite_ as disabled as you think it is would be ideal

**Comment by erka** [comment]
Are there advantages to consistently showing 'enabled' for boolean flags in UI? It will be easier to understand that some evaluation happens anyway for those flags.

![image](https://github.com/flipt-io/flipt/assets/19472/459ad42b-ec35-4a06-bc49-3e849b240baf)

**Comment by markphelps** [comment]
I think we can close this since #3300 was merged, as the table view will now show:

1. If evaluations will occur based on flag type / enabled property
2. If there is a default value if no rules match

let me know if you think this should be reopened @alexcardell
