### ISSUE TITLE
[Bug]: OCI registry with AWS ECR

### ISSUE THREAD

**Issue by thepabloaguilar** [flipt-io/flipt#3043]
### Bug Description

Hi guys, it's me (again 😆)! I've found something with the ECR integration that I was unable to see while the auth token doesn't expire and now with a stable deployment I started to see it.

The thing is, using the _aws-sdk_ is indeed working to get the authorization token but when the token expires it doens't get refreshed by _oras_ and the reason is simple, the returned error by the ECR API is:
```text
response status code 403: denied: Your authorization token has expired. Reauthenticate and try again.
```

The response returned a _403_ and not a _401_, the key difference is: _401_ returns the auth challange (_Www-Authenticate_ header) and _403_ don't! So we never get re-authenticadet again because _oras_ only will call the credentials function if a challange is returned.

### Version Info

[v1.41.1](https://github.com/flipt-io/flipt/releases/tag/v1.41.1)

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

Configures a Flipt instance using OCI with AWS ECR and wait the auth token to expire!

### Expected Behavior

After the token expires it should be able to re-authenticated again!

**Comment by thepabloaguilar** [comment]
A possible solution to this problem is:
* Disable cache when `aws-ecr` is chosen as we know the ECR API will always return a _403_ when to token has expired
* Modify the ECR struct to keep track when the token expire and renew the auth token some minutes before

**Comment by thepabloaguilar** [comment]
I could work on this if needed

**Comment by thepabloaguilar** [comment]
In fact it doesn't reach the challange piece of code, oras has this check:
```go
if resp.StatusCode != http.StatusUnauthorized {
    return resp, nil
}
```
[Source](https://github.com/oras-project/oras-go/blob/6fce64e956e850a3af7ea16e85959c23e3eddc4b/registry/remote/auth/client.go#L207)

In this bug the response status is "Forbidden" which will make the if statement condition to pass

**Comment by erka** [comment]
Hey @thepabloaguilar. 

Thank you for the report. 

I still need to read more AWS docs when http code 403 could be returned to finalize it. What do you think about #3044?

**Comment by markphelps** [comment]
> In fact it doesn't reach the challange piece of code, oras has this check:
> 
> ```go
> if resp.StatusCode != http.StatusUnauthorized {
>     return resp, nil
> }
> ```
> 
> [Source](https://github.com/oras-project/oras-go/blob/6fce64e956e850a3af7ea16e85959c23e3eddc4b/registry/remote/auth/client.go#L207)
> 
> In this bug the response status is "Forbidden" which will make the if statement condition to pass

@thepabloaguilar thanks for reporting! would this be a bug in ORAS then that we could open/issue a patch for? or do you think its only related to how we are using the ORAS client?

**Comment by thepabloaguilar** [comment]
That's a great question @markphelps, I think it's not _ORAS_ issue since it's behaving as it should be as the challange is only returned by _Forbidden_ status code. I do think it's an AWS Issue, at least for my understanding because I think if my token is expired I'm not forbbiden, I'm unauthorized, I no longer have a valid token so I don't have access to anything

**Comment by markphelps** [comment]
> Hey @thepabloaguilar.
> 
> Thank you for the report.
> 
> I still need to read more AWS docs when http code 403 could be returned to finalize it. What do you think about #3044?

I like @erka 's solution here! Just need to update to add the header like @thepabloaguilar mentioned

**Comment by thepabloaguilar** [comment]
Me too @markphelps, that should be enough

**Comment by thepabloaguilar** [comment]
Fixed by the @erka PR
