### ISSUE TITLE
Allow trust self-signed or trust insecure TLS certificate

### ISSUE THREAD

**Issue by YihongGao** [flipt-io/flipt#3105]
### Problem

When I want to use Cache feature with Redis if the Redis certificate is self-signed will start failed with this error message
```
    _________       __ 
   / ____/ (_)___  / /_
  / /_  / / / __ \/ __/
 / __/ / / / /_/ / /_  
/_/   /_/_/ .___/\__/  
         /_/           

Version: v1.42.0
Commit: 5ac6a4f16e8ac9d0eb931486b06fbddc62857d0d
Build Date: 2024-05-15T13:58:18Z
Go Version: go1.22.2
OS/Arch: linux/amd64

A newer version of Flipt exists at https://github.com/flipt-io/flipt/releases/tag/v1.42.1, 
please consider updating to the latest version.
Error: connecting to redis: tls: failed to verify certificate: x509: certificate signed by unknown authority
```

In my case, I use the GCP Memorystore(Redis)，the redis certificate singed by google.

### Ideal Solution

maybe added some configuration can be one of them:
1. trust insecure TLS certificate
    like `--insecure` argument in redis-cli or `InsecureIgnoreHostKey` in go-redis-client

2. set self-signed TLS certificate to be trust.
    like 
    ````
     ./src/redis-cli --tls \
    --cert ./tests/tls/redis.crt \
    --key ./tests/tls/redis.key \
    --cacert ./tests/tls/ca.crt
    ````

### Search

- [X] I searched for other open and closed issues before opening this

**Comment by GeorgeMac** [comment]
We can definitely extend our own configuration to support these extra TLS paramters passed to Redis 👍 

For context, whenever someone gets a chance to implement:

Here is where we configure the redis client used by the cache:
https://github.com/flipt-io/flipt/blob/8633edfb2127e42d2a0afdb9c45db66a71d13b5a/internal/cmd/grpc.go#L520-L523

Here is where the redis configuration lives in Flipt's configuration:
https://github.com/flipt-io/flipt/blob/8633edfb2127e42d2a0afdb9c45db66a71d13b5a/internal/config/cache.go#L92-L105

As you have suggested here @YihongGao I think we could add support for fields such as:
- Certificate (Perhaps both the raw key or a path to the key)
- PrivateKey (Again potentially a field for both raw + path)
- CACertficate (Again potentially a field for both raw + path)
- InsecureSkipVerify

**Comment by markphelps** [comment]
Closing now since this was added in #3107 . This will go out this coming week in next release!
