### ISSUE TITLE
[FLI-1067] Kafka Audit Sink

### ISSUE THREAD

**Issue by markphelps** [flipt-io/flipt#3146]
### Problem

Flipt currently supports audit event sinks to 3 places:
- [log file](https://docs.flipt.io/configuration/overview#audit-events-log-file) soon to also be stdout, see #3101 
- [webhooks](https://docs.flipt.io/configuration/overview#audit-events-webhook)
- [flipt cloud](https://docs.flipt.io/cloud/features/audit-logs)

I think we could get support for several other sinks by adding a message broker/queue such as Kafka, especially with projects like [Redpanda Connect](https://docs.redpanda.com/redpanda-connect/about/) (previously Benthos RIP 💀 )

### Ideal Solution

Add a new sink type `kafka`, which would send audit events to configured Apache Kafka message brokers

configuration may look like:

```yaml
audit:
  sinks:
    kafka:
      enabled:
      topic: foo
      bootstrap_servers:
        - my-cluster-kafka-bootstrap.kafka:9092
```

It seems `bootstrap_servers` are the new `broker_lists` ? https://stackoverflow.com/questions/50312579/what-is-difference-between-broker-list-and-bootstrap-servers

I haven't used Kafka in years though so I could be wrong

### Search

- [X] I searched for other open and closed issues before opening this

### Additional Context

Would love to know if any existing users would find this functionality useful

<sub>[FLI-1067](https://linear.app/flipt/issue/FLI-1067/kafka-audit-sink)</sub>

**Comment by thepabloaguilar** [comment]
@markphelps I'd like to suggest this library here: [franz-go](https://github.com/twmb/franz-go)

It's feature complete (compression, transaction, TLS, SASL Auth) and has support not only for vanilla Kafka but for Redpanda, Microsoft Event Hubs, and MSK too

**Comment by markphelps** [comment]
Great suggestion @thepabloaguilar !!!
