### ISSUE TITLE
evaluate constraints  against lists

### ISSUE THREAD

**Issue by giddel** [flipt-io/flipt#318]
Currently a constraint  can be evaluated against one value as in string comparison.
But our use cases often contain a list of values. A constraint should match, when the property of the segments occurs in a list e.g. a segment "Good Colors" should match on the property:

    myColor in (red, green, blue, yellow, purple)

instead of an writing a MatchAny with a lot of clicks in the UI:

```
myColor == red
myColor == green
myColor == blue
myColor == yellow
myColor == purple
```
Since our lists ca contain up to 50 entries it would save a lot of configuration work and avoid a lot constraints in the database ...
Finally it ends in a "LIST_COMPARISON_TYPE" or similar.

**Comment by giddel** [comment]
In addition to the above it would be nice if a property can be a list and it's checked if a concrete value is part of the list:
```
property: myColors=(red, green, blue, yellow, purple)
constraint: myColors contains "red"   # Match
constraint: myColors contains "black"   # No Match
```

**Comment by markphelps** [comment]
Im going to close this for now and keep it labeled as v2 as it would require a breaking change to the public API. Will re-evaluate for the next major version

**Comment by markphelps** [comment]
Going to re-open this as we got another request for this. Im not sure why I said it would be a breaking change because its adding a new operator type (I think).

Need to think about this a bit more however

One question is how many items should we allow in the list? 

We could put a hard limit for the database value and a soft limit for the UI.. since we wouldn't want to show/allow adding arbitrary values in the UI.

What do you think would be a good set of limits @giddel ?

**Comment by giddel** [comment]
It's hard to say. 
50 entries would be a good amount for our use case - until now. But may be it's not enough for the future. If we need more values per list - maybe we could split in in 2 ore more lists.
Or you set a default list size to 50 but it can overwritten by configuration if needed.

**Comment by sashayakovtseva** [comment]
+1 for list constraints

**Comment by dowglaz** [comment]
+1

**Comment by wallforfry** [comment]
Need list constraints too 👍

**Comment by phenax** [comment]
+1

**Comment by markphelps** [comment]
Yes please @phenax ! Great idea with JSON array

**Comment by markphelps** [comment]
This is now out in the latest release!! https://github.com/flipt-io/flipt/releases/tag/v1.31.0

Thanks again @phenax for fixing this long running feature request!!

**Comment by giddel** [comment]
Thanks a lot!
