### ISSUE TITLE
[Bug]: Error migrating database from version 11 to 12

### ISSUE THREAD

**Issue by giddel** [flipt-io/flipt#3333]
### Bug Description

I want to update my Flipt from v1.38.1 to v1.46.2 and got this error on mysql  database migration:
```   	
{"level":"WARN","time":"2024-07-30T08:37:44Z","msg":"configuration warning","message":"\"authentication.exclude.metadata\" is deprecated and will be removed in a future release. This feature never worked as intended. Metadata can no longer be excluded from authentication (when required)."}
{"level":"DEBUG","time":"2024-07-30T08:37:44Z","msg":"configuration source","path":"/etc/flipt/config/default.yml"}
{"level":"DEBUG","time":"2024-07-30T08:37:44Z","msg":"using driver","driver":"mysql"}
{"level":"DEBUG","time":"2024-07-30T08:37:44Z","msg":"current migration","current_version":11,"expected_version":12}
{"level":"DEBUG","time":"2024-07-30T08:37:44Z","msg":"running migrations..."}
 Error: running migrator running migrations: migration failed in line 0: ALTER TABLE namespaces ADD COLUMN state_modified_at TIMESTAMP;
 (details: Error 1067 (42000): Invalid default value for 'state_modified_at')
```
Flipt runs well with this database "error". Maybe that's because we do not use namespaces now.

Howto fix the database scheme?

### Version Info

v1.46.2 

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

Run `flipt migrate` in version v1.46.2 on a  v1.38.1  mysql database (Mysql version 5.7)

### Expected Behavior

Migration should run without error.

### Additional Context
Current database structure:
```
mysql> select * from namespaces;
+---------+---------+-------------------+-----------+----------------------------+----------------------------+
| key     | name    | description       | protected | created_at                 | updated_at                 |
+---------+---------+-------------------+-----------+----------------------------+----------------------------+
| default | Default | Default namespace |         1 | 2023-10-17 07:36:40.862812 | 2023-10-17 07:36:40.862812 |
+---------+---------+-------------------+-----------+----------------------------+----------------------------+
1 row in set (0,03 sec)

mysql> desc  namespaces;
+-------------+--------------+------+-----+----------------------+-------+
| Field       | Type         | Null | Key | Default              | Extra |
+-------------+--------------+------+-----+----------------------+-------+
| key         | varchar(255) | NO   | PRI | NULL                 |       |
| name        | varchar(255) | NO   |     | NULL                 |       |
| description | text         | NO   |     | NULL                 |       |
| protected   | tinyint(1)   | NO   |     | 0                    |       |
| created_at  | timestamp(6) | NO   |     | CURRENT_TIMESTAMP(6) |       |
| updated_at  | timestamp(6) | NO   |     | CURRENT_TIMESTAMP(6) |       |
+-------------+--------------+------+-----+----------------------+-------+
6 rows in set (0,03 sec)
```

**Comment by erka** [comment]
Hey @giddel. Thank you for your bug report. 

It looks like Mysql 5.7 doesn't allow `timestamp` to be set to `null`.  Ideally, the correct migration for your version of Mysql should be

```sql
ALTER TABLE namespaces ADD COLUMN state_modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
```

**Comment by erka** [comment]
@giddel You could run these queries manually as workaround for the problem.

```sql
ALTER TABLE namespaces ADD COLUMN state_modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
UPDATE schema_migrations SET dirty=0 WHERE version = 12;
```

**Comment by markphelps** [comment]
thanks @erka !! maybe we should put a warning that Flipt only supports MySQL 8+? (weird they went from 5.7 to 8 btw..)

but 5.7 reached EOL back in October 2023 according to my Googles

**Comment by erka** [comment]
@markphelps It's a bit difficult one. Some folks prefer 5.7 over 8 because of [performance](https://www.percona.com/blog/mysql-8-is-not-always-faster-than-mysql-5-7/). 

What impact could be if we fix that mysql migration by adding `DEFAULT CURRENT_TIMESTAMP;` to it? If we can do that people will use Flipt with 5.7 too.

**Comment by markphelps** [comment]
Yeah i think we can. It shouldnt break anything afaik

**Comment by giddel** [comment]
Thanks for your input guys!
We have already planned to migrate our Mysql version. In the meantime I'm will adjust the database schema manually.

**Comment by markphelps** [comment]
cheers @giddel !

We could add an IT that runs with Mysql 5.7 to verify these kinds of issues don't sneak there way in again
