### ISSUE TITLE
Bug: regression in our support for `postgresql://` scheme in DB URL

### ISSUE THREAD

**Issue by GeorgeMac** [flipt-io/flipt#3351]
When we moved from `lib/pq` to `pgx` we accidentally dropped support for the long form `postgresql://` scheme:
https://github.com/flipt-io/flipt/pull/2996/files#diff-4e7891eb51746a9a9bca80d8c406f025727fd7e3bd5644de4170560abc15fa70R52-R54

As per a discussion in Discord: https://discord.com/channels/960634591000014878/1269927225717952583/1269927225717952583

A user attempted to upgrade from 1.38 to 1.47 and discovered the migrations were failing due to an unknown database scheme.
They were using the originally supported `postgresql://` scheme.
Looks like it is easy enough for us to support an additional alias for this scheme to avoid it causing anyone else issues in the future.

**Comment by radekska** [comment]
Hey @GeorgeMac, let me solve the issue.

**Comment by GeorgeMac** [comment]
Nice on @radekska !
