### ISSUE TITLE
[Bug]: export fails on variant flag with no rules

### ISSUE THREAD

**Issue by danilobuerger** [flipt-io/flipt#3417]
### Bug Description

If you create a variant flag that does not have rules yet, the export will error out with
> wrong format for rule segments

### Version Info

1.48.1

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

1) create a variant flag
2) export

### Expected Behavior

The export should work even if there are no rules attached

**Comment by erka** [comment]
Hi @danilobuerger. Thank you for your bug report

I can't repo the problem with your steps. This issue could happen when some rule has the reference to the deleted segment. This most-likely is related to #2403.

**Comment by PlkMarudny** [comment]
I am having the same error, but somehow I am unable to find a rule that references a deleted segment (probably because no segment was ever deleted). So what to do in such a case?

**Comment by PlkMarudny** [comment]
Sure, will `flipt.db` do the trick?

**Comment by erka** [comment]
Yep, it will do the trick. Could you please tell us the version of Flipt you are using as well?

**Comment by PlkMarudny** [comment]
1.47.1

**Comment by PlkMarudny** [comment]
[flipt.zip](https://github.com/user-attachments/files/17339661/flipt.zip)

**Comment by erka** [comment]
@PlkMarudny thank you for sharing this with us. 

Just a heads up. There are two flags `agency`(one rule `8fa497aa-74c9-41fd-bb34-6e288626669b`) and `content_type`(two rules `228724f7-dce9-4e53-9dc5-0dadce2abb0e` and `8a698eb0-016e-453d-88ab-d646f4c7fcea`) which are broken. Both have rules without segments. The weird thing is that UI doesn't display those rules and it looks like everything is correct. The only insight that something is out of order that `content_type` flag is missing rule number 5.

**Comment by erka** [comment]
@danilobuerger What database do you use for Flipt?

**Comment by PlkMarudny** [comment]
No problem, I understand. Thanks for that.

**Comment by danilobuerger** [comment]
Thats awesome, thanks for fixing it!
