### ISSUE TITLE
[Bug]: OpenFeature provider returns default value set in .getObjectDetails() instead of the default value set in Flipt, if matches 

### ISSUE THREAD

**Issue by PlkMarudny** [flipt-io/flipt#3418]
### Bug Description

Not sure if this is really a bug, but if a default rule matches context,  `@openfeature/flipt-provider` returns `reason: DEFAULT` in `getObjectDetails()` and uses the default value defined in `getObjectDetails()`. In theory it makes sense, but the default rule seems to be mandatory anyway inside Flipt, so why not to return it? In the current setup, this requires defining the default value in client code and make the default rule in Flipt somehow useless.

### Version Info

    _________       __ 
   / ____/ (_)___  / /_
  / /_  / / / __ \/ __/
 / __/ / / / /_/ / /_  
/_/   /_/_/ .___/\__/  
         /_/           

Version: v1.48.1
Commit: 64b76076bac98dcd2eaefd5bd51c14ecb2aef0d3
Build Date: 2024-08-16T12:13:19Z
Go Version: go1.22.6
OS/Arch: linux/amd64

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

Use OpenFeature provider and construct a context that triggers the default rule for a flag (I used Object, which is especially painful to handle) 

### Expected Behavior

I would prefer to have the default value returned.

### Additional Context

Docker

**Comment by erka** [comment]
Thank you for your report @PlkMarudny 

It would be helpful if you could share the js code and the flags configuration example.

**Comment by erka** [comment]
@PlkMarudny the issue should be resolved. Please update `@openfeature/flipt-provider` to `0.1.1`.

**Comment by PlkMarudny** [comment]
Thank you very much. I think this made the whole product more logical,
right?

**Comment by erka** [comment]
I agree that was an issue. Thank you for your bug report.
