### ISSUE TITLE
Allow trust self-signed or trust insecure TLS certificate on git backend

### ISSUE THREAD

**Issue by lostekos** [flipt-io/flipt#3432]
### Problem

If I try to use a git backend with a certificate from not know authority I get _failed to verify certificate: x509: certificate signed by unknown authority_ error. I tried to set _storage.git.insecure_skip_tls_ to false, _ca_cert_path_ or _ca_cert_bytes_ options in configuration file, but I was not successful with any of them.

```console
/ $ ./flipt --config /var/opt/flipt/c/default.yml 
2024-09-02T12:57:04Z    DEBUG   configuration source    {"path": "/var/opt/flipt/c/default.yml"}

    _________       __ 
   / ____/ (_)___  / /_
  / /_  / / / __ \/ __/
 / __/ / / / /_/ / /_  
/_/   /_/_/ .___/\__/  
         /_/           

Version: v1.48.1
Commit: 64b76076bac98dcd2eaefd5bd51c14ecb2aef0d3
Build Date: 2024-08-16T12:13:19Z
Go Version: go1.22.6
OS/Arch: linux/amd64

2024-09-02T12:57:04Z    DEBUG   checking for updates
2024-09-02T12:57:04Z    DEBUG   version info    {"current_version": "v1.48.1", "latest_version": "1.49.0"}
A newer version of Flipt exists at https://github.com/flipt-io/flipt/releases/tag/v1.49.0, 
please consider updating to the latest version.
2024-09-02T12:57:04Z    DEBUG   local state directory exists    {"path": "/home/flipt/.config/flipt"}
2024-09-02T12:57:04Z    DEBUG   starting telemetry reporter     {"component": "telemetry"}
2024-09-02T12:57:04Z    DEBUG   last report     {"component": "telemetry", "when": "2024-09-02T12:24:20Z", "elapsed": "32m44.948102275s"}
Error: performing initial fetch: Get "https://myhost/flipt.git/info/refs?service=git-upload-pack": tls: failed to verify certificate: x509: certificate signed by unknown authority
```
This is my config:

```yaml
log:
  encoding: console
  grpc_level: ERROR
  level: DEBUG
server:
  grpc_port: 9000
  host: 0.0.0.0
  http_port: 8080
  https_port: 443
  protocol: http
storage:
  type: git
  git:
    authentication:
      basic:
        password: user
        username: pass
    poll_interval: 30s
    ref: main
    repository: https://myhost/flipt.git
    insecure_skip_tls: true
    ca_cert_path: /var/opt/flipt/cert/ca.pem
```

### Ideal Solution

Get those storage.git.insecure_skip_tls, ca_cert_path, ca_cert_bytes configuration options to work. Necause they are not documented anywhere I am labeling this as enhancement and not as bug.

### Search

- [X] I searched for other open and closed issues before opening this

**Comment by GeorgeMac** [comment]
I just checked and those parameters should be wired up as expected.
There are even unit tests around it (no integration tests though - note for future).
So, seems like something else is wrong here:
https://github.com/flipt-io/flipt/blob/cb603f7bf670d7ad01a589991630a9a4cd47214b/internal/storage/fs/git/store_test.go#L525-L532

**Comment by GeorgeMac** [comment]
I think I see the bug. It is not being passed in here:
https://github.com/flipt-io/flipt/blob/cb603f7bf670d7ad01a589991630a9a4cd47214b/internal/storage/fs/git/store.go#L308-L311

We can get that fixed up and in a patch release.

**Comment by GeorgeMac** [comment]
Sorry, GitHub auto closed this as the fix is now merged into main.
We can get this into a patch release soon and then you can use it 👍
