### ISSUE TITLE
[Bug]: Variant type flags webhook payloads does not include "default rule" change

### ISSUE THREAD

**Issue by alucarddelta** [flipt-io/flipt#3471]
### Bug Description

When sending webhook events and a the default rule is changed for a variant type flag, there is no information sent on what the default rule was changed to.

In the example, I changed the default rule from testvar to testvar2.

```JSON
{
  "version":"0.2","type":"flag","action":"updated","metadata":{
    "actor":{
        "authentication":"oidc","email":"user@email.com.au","ip":"192.168.1.1","name":"user"}
    },
    "payload":{
        "description":"","enabled":true,"key":"test","name":"test","namespace_key":"default"
    },
  "timestamp":"2024-09-17T02:50:06Z"}
```

Bool type flag default "rollout" changes the "enable" object
``` JSON
{"payload":{"description":"","enabled":false,"key":"testbool","name":"testbool","namespace_key":"default"}}
{"payload":{"description":"","enabled":true,"key":"testbool","name":"testbool","namespace_key":"default"}}
```

### Version Info

1.48.1

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

1. Configure the server to sent webhooks
2. Create a Flag of type Variant
3. Create 2 Variants
4. Set the Flag to 1
5. Update the Flag to 2

### Expected Behavior

As part of the Payload object in the webhook include the name/key of the variant that is being used
``` JSON
    "payload":{
        "description":"","enabled":true,"key":"test","name":"test","namespace_key":"default", "default_rule":"testvar2"
    },
```

**Comment by GeorgeMac** [comment]
Thanks for raising this @alucarddelta 🙏 

I believe this needs adding roughly here in the code (for future reference):
https://github.com/flipt-io/flipt/blob/ebca332effc1ee0852b5b18392935c4f0e4335f6/internal/server/audit/types.go#L10-L26
