### ISSUE TITLE
Invalid Attachment Validation

### ISSUE THREAD

**Issue by MMartyn** [flipt-io/flipt#3594]
The attachment validations appears to be wrong. In it's current form it is restricting attachments to less than 10 KB, but stating that the size limit is 10000 KB. Reviewing cockroach DB's JSONB type, there is no limit so I would assume that this was intended to be maxJsonStringSize * 1024

https://github.com/flipt-io/flipt/blob/b1c92b33217c7e131f5546baa26e67a5a8f3e59f/rpc/flipt/validation.go#L35

**Comment by markphelps** [comment]
Hey @MMartyn ! Good catch! So it is indeed less than 10kb as it stands as it allows for 10,000 bytes. If we wanted to make it 10kb we'd need to do 

```
maxJsonStringSize = 10 * 1024  // 10 KB in bytes
```

> but stating that the size limit is 10000 KB

Where is this stated just curious? We can definitely bump the max size up, but 10,000 kb is almost 10mb

**Comment by MMartyn** [comment]
> Where is this stated just curious? We can definitely bump the max size up, but 10,000 kb is almost 10mb
I agree 10mb seems a bit much. I lowered it to 1mb and created a PR.
