### ISSUE TITLE
[Bug]: Helm Chart migrations do not mount PVC for persistence feature

### ISSUE THREAD

**Issue by lukas-reining** [flipt-io/flipt#3616]
### Bug Description

Hey, when using `--set migrations.enabled=true`, and using `--set persistence.enabled=true` with `SQLite`, migrations fail because the persistent volume is not mounted into the pod of the migration job.
For testing and eval systems, using the SQLite is good enough and so it would be good to also be able to run the migrations automatically on them.
I created a copy of the migration job pod with the PVC mounted and it worked well!

This is where it is missing:
https://github.com/flipt-io/helm-charts/blob/46bff269753a5440cff26d3599a08ffdf85be7da/charts/flipt/templates/migration_job.yaml#L56-L63

And this is how it works for the real flipt Pod: 
https://github.com/flipt-io/helm-charts/blob/46bff269753a5440cff26d3599a08ffdf85be7da/charts/flipt/templates/deployment.yaml#L102-L114

### Version Info

Helm Chart version: 0.72.2
Flipt version: v1.51.1

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

Install an older flipt version, using the Helm Chart, with persistence using SQLite enabled and enable migrations.
Then upgrade to the newest chart.

**Comment by lukas-reining** [comment]
Opened a PR to fix this here: https://github.com/flipt-io/helm-charts/pull/185

**Comment by GeorgeMac** [comment]
Thanks for raising and addressing this @lukas-reining !
