### ISSUE TITLE
[Bug]: Incorrect JSON serialization tag

### ISSUE THREAD

**Issue by Vasco-jofra** [flipt-io/flipt#3657]
### Bug Description

Hi! While doing a quick code search, I found the following code, which incorrectly exposes the `ClientID` field with the `-` key. This is caused by the `json:"-,omitempty"` tag; by adding the `,` after the `-`, the `-` becomes the field key.

https://github.com/flipt-io/flipt/blob/f2e1b1ce08a0627c44947c20b8dcbcda8f36437a/internal/config/authentication.go#L482-L483

### Version Info

.

### Search

- [X] I searched for other open and closed issues before opening this

### Steps to Reproduce

You can confirm this Go behavior with the following script:
```go
package main

import (
	"encoding/json"
	"fmt"
)


func main() {
	type Test struct {
		ClientID string `json:"-,omitempty"`
	}
	u := Test{}
	_ = json.Unmarshal([]byte(`{"-": "asd"}`), &u)
	fmt.Printf("Result: %#v\n", u)
	// Result: main.Test{ClientID:"asd"}
}
```

### Expected Behavior

.

**Comment by erka** [comment]
Thank you @Vasco-jofra for a bug report!

**Comment by JLLeitschuh** [comment]
Is this a security vulnerability? Does this expose data that shouldn't have been exposed?

**Comment by Vasco-jofra** [comment]
@JLLeitschuh I don't have the context of how this is used in the code, but at most it exposes the `ClientID`, not the `ClientSecret`,  so I don't think there's security impact.
