### ISSUE TITLE
Restrict namespace listing based on user authorization

### ISSUE THREAD

**Issue by andi4000** [flipt-io/flipt#3686]
## Context
Consider the following namespaces available on the instance:
- team1
- team2
- team3

and following rego policy
```
package flipt.authz.v1
import rego.v1

default allow := false

allow if {
    claims := json.unmarshal(input.authentication.metadata["io.flipt.auth.claims"])
    "member-team1" in claims.roles
    input.request.namespace in ["team1"]
}
```

## Problem
Currently, a user with role `member-team1` is able to see **all** namespaces in the UI. `GET /api/v1/namespaces` returns **all** namespaces, even those for which the user lacks authorization. 

While the system correctly blocks navigation to unauthorized namespaces, this behaviour exposes namespace information that the user should not have access to. Solving this would prevent information leakage and improving UX by aligning namespace visibility with access permission.

### Ideal Solution

Ideally, the `GET /api/v1/namespaces` endpoint should return only the namespaces that the user is authorized to access, based on the defined rego policy.

### Search

- [X] I searched for other open and closed issues before opening this

**Comment by andi4000** [comment]
Upon further investigation I don't think this is a feature request but rather a bug: #3688

**Comment by erka** [comment]
@andi4000  There is a new nightly build (`ghcr.io/flipt-io/flipt:v1.53.3-nightly`). If you could try it we would like to hear your feedback if your issue is resolved.

**Comment by andi4000** [comment]
I'm going to test this after the Christmas break and get back to you! Thank you @erka  ❤️
