### ISSUE TITLE
Targeting the intersection of multiple segments in a single rule

### ISSUE THREAD

**Issue by jalaziz** [flipt-io/flipt#732]
**Is your feature request related to a problem? Please describe.**

We've started to rollout `flipt` and mostly love it. However, we have encountered a few limitations in the way segments and rules are defined. In particular, the lack of full boolean logic makes certain configurations quite verbose. For example, it's difficult to create a target that matches "all dev environments and all API users" where "all dev environments"  is defined as "staging, nightly, etc".

**Describe the solution you'd like**

We'd like to see the ability to define targeting rules as a boolean combination of segments. While we can technically achieve "OR" combinations by defining multiple rules, "AND" combinations are much harder to accomplish. In order to achieve this today, we would have to create segments for every combination we would like to target; however, since segment constraints don't support combining logical operators, this is also limited.

This is somewhat related to #318, but also more general and focused on targeting rules.

**Additional context**

We'd be happy to help contribute this, but I wanted to start the discussion to ensure the request makes sense for the broader project.

**Comment by markphelps** [comment]
@jalaziz Thanks for the issue. I really like this idea. I'm trying to visualize how this could best be displayed to the user in the UI. 

One idea is to simply allow you to specify multiple segments in the rule creation, and the UI would inform the user that this is an ANDing of the two segments.

Another potential solution that comes to mind is to support something like 'rule groups' where you can AND two rules together, but that might get complicated when it comes to distributions.

I would definitely welcome contributions on this, even if its just a mockup of how you would expect the user interaction to work from a UI and API perspective.
