### ISSUE TITLE
Cache improvement: ListFlags

### ISSUE THREAD

**Issue by AyWa** [flipt-io/flipt#935]
**Describe the bug**

* `ListFlags` should be cache by flipt when `cache is enable`. Right now it will [always call the storage](https://github.com/markphelps/flipt/blob/06aa76d28970a6b8fe533ba098b91ff7ad01cd74/storage/cache/flag.go#L53)
* When a key is not in storage, it seems we defer to the [underlying storage](https://github.com/markphelps/flipt/blob/main/storage/cache/flag.go#L38), so if there is a lot of req/s, we might call the db multiple times. I would suggest that we try to call the db only once

**Version Info**

main branch

**Comment by AyWa** [comment]
@markphelps Sounds good ! 

> My only concern with caching the List Flags response would be the number of flags that could potentially be returned which could cause the cache to 'overflow'.

Yeah thats true that it could be a problem, I agree that setting a default + max batch size might help to ensure we dont overflow the cache !

**Comment by erka** [comment]
@markphelps do you actually want do to this?  I believe `ListFlags` probably isn't called a lot of times(web ui/import/export). Web UI should cache the list for some time, `export/import` one time operation. Could you guide me where I have blind spot?

**Comment by markphelps** [comment]
Yeah I think I agree. Going to close this for now
