### ISSUE TITLE
Migrate to a different logger

### ISSUE THREAD

**Issue by markphelps** [flipt-io/flipt#964]
Sadly it is time to say goodbye to [logrus](https://github.com/sirupsen/logrus) as it has been put in maintenance mode by its creator.

I'm thinking of moving the internal logger to something like [zap](https://github.com/uber-go/zap) as I've used it in the past and enjoyed it, however I'm open to other suggestions!

Main thing is though that I dont want to change the log format too much during this migration and ideally whichever logger we use can adapt to produce the same output that logrus currently produces

**Comment by daxartio** [comment]
Yeah, good!
