### ISSUE TITLE
Support CockroachDB

### ISSUE THREAD

**Issue by markphelps** [flipt-io/flipt#975]
### Problem

[cockroachDB](https://github.com/cockroachdb/cockroach) uses the same wire protocol as Postgres, so the application code _should_ not require any update to support it. 

### Ideal Solution

Describe the solution you'd like:

- [ ] Add CockroachDB as a supported backend DB storage protocol
- [ ] Support configuring cockroachDB in the config.yml
- [ ] Add example on how to run Flipt with CockroachDB [Example with Docker Compose](https://gist.github.com/dbist/ebb1f39f580ad9d07c04c3a3377e2bff)

### Additional Context

We'll likely need to update the config to support cockroach db however, as we need to tell the migrator (golang-migrate) that we are actually using Cockroach and not PG. [Example](https://github.com/golang-migrate/migrate/tree/master/database/cockroachdb)

**Comment by z0mb1ek** [comment]
+1

**Comment by markphelps** [comment]
Coming soon
