### ISSUE TITLE
Json log formatter

### ISSUE THREAD

**Issue by daxartio** [flipt-io/flipt#992]
### Problem

I want to configure log formatter of server, for example, use json formate in log output.

### Ideal Solution

From env to receive log format and to configure logrus.

```go
import (
  log "github.com/sirupsen/logrus"
)

func init() {
  if EnvLogFormat == "json" {
    log.SetFormatter(&log.JSONFormatter{})
  } else {
    log.SetFormatter(&log.TextFormatter{})
  }
}
```

**Comment by markphelps** [comment]
thanks @daxartio , I agree this would be a great feature. I'm actually looking into replacing logrus with zap or similar #964, so I wonder if it would make sense to implement this as part of that work?

**Comment by daxartio** [comment]
Yeah, good!
